### ISSUE TITLE
Type ERROR (undefined)

### ISSUE THREAD

**Issue by theamzngq** [OctoFarm/OctoFarm#1013]
### OctoFarm Version

1.2.2

### OctoPrint Version(s)

1.7.3

### pm2 or docker?

pm2

### Operating System

Ubuntu

### Location of the problem

Web Interface

### Description of the problem

```markdown
Cannot read properties of null (reading 'length')
FILE INFO
LINE: undefined
COL: undefined
STACK:
TypeError: Cannot read properties of null (reading 'length') at Je (http://192.168.0.75:4000/assets/dist/panel-view.runner.min.js:2:814020) at Ge (http://192.168.0.75:4000/assets/dist/panel-view.runner.min.js:2:802974) at HTMLButtonElement. (http://192.168.0.75:4000/assets/dist/panel-view.runner.min.js:2:816291)
```

### Steps taken to reproduce

click **Job** button from panel view

### What did you expect to happen

job details

### To avoid the problem I had to

no avoiding it

[octofarm_dump-5-27-2022-9-03-51 AM.zip](https://github.com/OctoFarm/OctoFarm/files/8787943/octofarm_dump-5-27-2022-9-03-51.AM.zip)
t

**Comment by NotExpectedYet** [comment]
Cheers for the report, hoping to get a bugfix release for 1.2.3 out sometime this weekend, have added this to the list of to-do.
