### ISSUE TITLE
Filament Manager plugin doesn't correctly generate spool list on clients

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#1066]

**Comment by nokemono42** [comment]
Here is a log dump from my OctoFarm instance

[octofarm_dump-6-8-2022-1-49-21 PM.zip](https://github.com/OctoFarm/OctoFarm/files/8863902/octofarm_dump-6-8-2022-1-49-21.PM.zip)
.

**Comment by NotExpectedYet** [comment]
> Here is a log dump from my OctoFarm instance
> 
> [octofarm_dump-6-8-2022-1-49-21 PM.zip](https://github.com/OctoFarm/OctoFarm/files/8863902/octofarm_dump-6-8-2022-1-49-21.PM.zip) .

I think the problem was the hideEmpty setting, seemed to only generate the list with it on... will have a fix shortly.
