### ISSUE TITLE
OctoPrint User Not Listed

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1081]
### OctoFarm Version

1.2.7

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Server

### Description of the problem

```markdown
I have 3 users setup in OP.
myself (first created user)
service.prusaslicer
service.octofarm

Application keys have been generated for service.octofarm user on 3x OP instances.
service.octofarm user has Admin and Operator permissions in OP.

Previously on 1.2.6 when entering the application key for service.octofarm, 2 users appeared for selection myself and service.octofarm.

Since building a fresh 1.2.7 instance of OF, using the same application keys the service.octofarm user isn't enumerated/listed. myself is the only account available.

This causes the printer state to show disconnected and not function correctly.
```

### Steps taken to reproduce

1. Install fresh 1.2.7 OF on fresh Ubuntu 20.04.4 LTS VM per OF installation guide.
2. Add printers with existing API keys setup

### What did you expect to happen

Expected the service.octofarm user to be available for selection on the printer.

### To avoid the problem I had to

Workaround by changing the API key to the one for myself and using that user in the short term.
[octofarm_dump-6-14-2022-1-46-58 PM.zip](https://github.com/OctoFarm/OctoFarm/files/8900373/octofarm_dump-6-14-2022-1-46-58.PM.zip)
![Screenshot 2022-06-14 213449](https://user-images.githubusercontent.com/95956617/173594508-93b24597-73b7-4159-a5b8-1ec8ae7ea670.png)

**Comment by NotExpectedYet** [comment]
Your current user won't be overriden when this is fixed in the next bug fix but going forward the new flow will be as follows:

- filter out all admin users
 - do a case-insensitive check for `OctoFarm` user
 - do a case-insensitive check if user name contains octofarm anywhere
 - finally fall back to grabbing the first user in the list
