### ISSUE TITLE
Filament section can't assign spool to tool 1 for second extruder for idex printer

### ISSUE THREAD

**Issue by enishi1357** [OctoFarm/OctoFarm#1085]
### OctoFarm Version

Latest 1.2.7

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu

### Location of the problem

Not sure

### Description of the problem

```markdown
No one to pop out a list of extruder to select tool 1 for second extruder
```

### Steps taken to reproduce

select filament tab

click spool manager

try to find tool 1 for idex printer

### What did you expect to happen

Show tool 1 that actually works

**Comment by NotExpectedYet** [comment]
What is your profile like in OctoPrint? 

Just so I can replicate when I test as I don't use an idex personally.

**Comment by enishi1357** [comment]
You mean this?

![image](https://user-images.githubusercontent.com/33684474/173729766-6182466f-caab-45a0-a5f8-b4507c3912be.png)

![image](https://user-images.githubusercontent.com/33684474/173729997-f1506dff-5464-413c-b98e-4bd9bc0ea451.png)


There's also as shown below a way to select tool 1 which is the second extruder and control it. Let me know if you like the drop down thingie shown as I'm printing something currently so I can't drop it yet.

![image](https://user-images.githubusercontent.com/33684474/173730114-ea2648f7-3427-4624-b512-8f36c1b56ece.png)

**Comment by NotExpectedYet** [comment]
Yeah perfect thanks! 

Will setup a test printer with that and find the bug this weekend :)

**Comment by NotExpectedYet** [comment]
Hello, is this with Filament Manager Plugin? I've just tried selecting the second tool and it seems to work fine this end.

**Comment by NotExpectedYet** [comment]
![Image](https://user-images.githubusercontent.com/61137988/174032337-d8d5040b-c161-4016-8e7d-1d06db253f24.png)

If it's not would you mind sending a screenshot of this screen please? 

It's in Printer Manager -> Manage dropdown -> Settings -> Profile

**Comment by NotExpectedYet** [comment]
I "think" 

![image](https://user-images.githubusercontent.com/61137988/174033940-47d7e688-30de-446c-bdbc-269f34e9da57.png)


That Update Information button may help if the profile tab only shows 1 extruder. I replicated you OP setup and it seems to work fine but I had to run Update information. 

I'll update the title if it's not correctly grabbing that information on first scan as it should be.

**Comment by enishi1357** [comment]
I'm confused. I'm using spool manager in Octoprint.

**Comment by enishi1357** [comment]
Nvm I found octoprint manager.

Lol I updated and my second extruder temperature and also control disappeared in octoprint

**Comment by NotExpectedYet** [comment]
> Nvm I found octoprint manager.
> 
> Lol I updated and my second extruder temperature and also control disappeared in octoprint
> 
> Update: Nvm it switched my profile to one that has one extruder.
> 
> rebooted my computer and the reheat only heat up first extruder

Yeah re-heat is broken, will sort that. Isn't taking the tool selection into acocunt when sending the command. 

I don't support spool manager, thats why this isn't working. I only support the filament manager plugin as spool manager doesn't support a database from last I checked. I've no real plans to add support for it either as I'd rather work on an OctoFarm focused spool manager. 

There's two options. Either setup Filament Manager Plugin, or use OctoFarms Filament Manager with the two new settings for Downdating cancelled and Successful prints here: 

![image](https://user-images.githubusercontent.com/61137988/174046867-bb718e85-2485-4cb0-baf2-77c4bd1b6975.png)

I'll close this now, please open if I mistakenly closed it.

**Comment by enishi1357** [comment]
if it helps my octoprint instance is installed on linux as well as octofarm on the same comnputer.

**Comment by NotExpectedYet** [comment]
The OctoPrint button I showed is in "Printers" 

The image above is in System -> Server -> Filament Manager hope that helps!
