### ISSUE TITLE
Health checks remain in failed state when all checks pass

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1086]
### OctoFarm Version

1.2.8

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Web Interface

### Description of the problem

```markdown
Health Check button remains in Alerts column on printers tab after alerts have been resolved.
```

### Steps taken to reproduce

1. Upgrade from 1.2.7 to 1.2.8
2. OF connects to all OP instances
3. Warning is displayed for printer port as the printer is currently switched off
4. Power on all printers and connect
5. Refresh settings on each or reconnect all sockets
6. Alert remains but states "No current printer health issues!"

### What did you expect to happen

The health button to be removed from the alerts section when no issues exist

### To avoid the problem I had to

[octofarm_dump-6-15-2022-10-20-33 AM.zip](https://github.com/OctoFarm/OctoFarm/files/8908371/octofarm_dump-6-15-2022-10-20-33.AM.zip)
![Screenshot 2022-06-15 182256](https://user-images.githubusercontent.com/95956617/173805365-87498547-2510-4b13-ba11-342d3cab75fa.png)
![Screenshot 2022-06-15 182329](https://user-images.githubusercontent.com/95956617/173805370-ed250477-7cd0-4902-98ee-7ad51ebce95e.png)

**Comment by NotExpectedYet** [comment]
Cheers, I missed something again. Will sort!
