### ISSUE TITLE
Pre-v1.2 Print History not available in /history UI Tab.

### ISSUE THREAD

**Issue by IHVD** [OctoFarm/OctoFarm#1088]
### OctoFarm Version

1.2.5

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

FarmPi

### OctoPrint Plugins

n/a

### Location of the problem

MongoDb

### Description of the problem

```markdown
Updated from 1.1.3 to 1.2.5, print history from previous build was not available on the new build.
Wanted to manually update my spools and how much filament they have left, but after the UI change I could not find the history.
```

### Steps taken to reproduce

1. Run a 1.1.3 OctoFarm.
2. Print some things.
3. Upgrade using the in-app button
4. Cry because you were not supposed to use the in-app button
5. Fix the installation.
6. Check your history, history gone!

### What did you expect to happen

History not gone! :D
I expected the history of pre-1.2 to be available so I could update my spools manually.

**Comment by NotExpectedYet** [comment]
I should have this fixed for the next build. 

I've written a new migration script that will regenerate the startDate / endDate key values that got wiped to 1970...
