### ISSUE TITLE
Power On command sent to printer, even if it's on

### ISSUE THREAD

**Issue by taker218** [OctoFarm/OctoFarm#1090]
### OctoFarm Version

1.2.8

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

docker

### Operating System

debian

### Location of the problem

Web Interface

### Description of the problem

```markdown
When I select a file and hit print, it seems like the power on command is sent to the printer, even if the printer is turned on (and shown as that in the webinterface as well)
```

### Steps taken to reproduce

1. Power on printer
2. Select file
3. press print

### What did you expect to happen

That the print command is sent directly, not the power on command

I attached a current logdump. If there is anything else you need, please let me know.

[octofarm_dump-6-16-2022-2-59-24 PM.zip](https://github.com/OctoFarm/OctoFarm/files/8919037/octofarm_dump-6-16-2022-2-59-24.PM.zip)

**Comment by NotExpectedYet** [comment]
It should read your state and only send if not, I'll double check it's actually doing that. Cheers for the report.
