### ISSUE TITLE
Can't Remove Printer Group

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1096]
### OctoFarm Version

1.2.9

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Web Interface

### Description of the problem

```markdown
I added a group to each of the printers, but when I try set it back to blank and press save it doesn't revert back to not having a group and retains its same group name.
```

### Steps taken to reproduce

1. Edit printer settings
2. Enter group name
3. Press save
4. Decided you don't want to use groups
5. Edit printer settings
6. Backspace/clear group name
7. Press save

### What did you expect to happen

The group to be removed from the printer

[octofarm_dump-6-17-2022-11-06-11 AM.zip](https://github.com/OctoFarm/OctoFarm/files/8926927/octofarm_dump-6-17-2022-11-06-11.AM.zip)

**Comment by NotExpectedYet** [comment]
Good spot! yeah the field expects another value inputting.
