### ISSUE TITLE
History Tab - Cost Calculation Issue

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1104]
### OctoFarm Version

1.2.11

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Web Interface

### Description of the problem

```markdown
History Tab - Combined Total cost doesn't match Filament Cost + Printer Cost.
History Tab - Average cost per hour doesn't calculate
History Tab > Statistics > $Costs/Usage (State statistics) > Print totals Per Month - Doesn't calculate total count
```

### Steps taken to reproduce

1. Print some things
2. Navigate to the History tab

### What did you expect to happen

Calculate correctly

### To avoid the problem I had to

![Screenshot 2022-06-19 202324](https://user-images.githubusercontent.com/95956617/174480805-9b773528-2fd2-4631-8f3c-604a9e0467b2.png)
![Screenshot 2022-06-19 202427](https://user-images.githubusercontent.com/95956617/174480808-5b317d3f-1c6e-44ef-959c-ff4c82d46d31.png)

**Comment by NotExpectedYet** [comment]
Huh, weird will take a look cheers for the report

What do you mean by the last one sorry? I can see the first too they're certainly incorrect. Think I know why. 

The last one seems to be calculating correctly, although you've not put a screenshot of the cost modal.

They only update once per day though which I did wonder if it was confusing or not but I wasn't sure on CPU usage for doing a full years worth of calculations like that on the database. I'll flood a database through and test see what it's like.

**Comment by SuperTrollMan** [comment]
re: point 3

The print totals per month graph reads successful prints: 9
Total prints: 0

Shouldn't total prints read the sum of all (failed, cancelled and success)?

Kind Regards

Sent from mobile, please excuse my brevity.

On Jun 19, 2022 21:19, James Mackay ***@***.***> wrote:

Huh, weird will take a look cheers for the report

What do you mean by the last one sorry? I can see the first too they're certainly incorrect. Think I know why.

The last one seems to be calculating correctly, although you've not put a screenshot of the cost modal.

They only update once per day though which I did wonder if it was confusing or not but I wasn't sure on CPU usage for doing a full years worth of calculations like that on the database. I'll flood a database through and test see what it's like.
