### ISSUE TITLE
Selected Octofarm spool not syncing with Octoprint spool

### ISSUE THREAD

**Issue by KKriz** [OctoFarm/OctoFarm#1109]
### OctoFarm Version

1.3.0

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

docker

### Operating System

Linux 5.15.46-Unraid (linux)

### Location of the problem

Not sure

### Description of the problem

```markdown
The Octofarm spool manager is not syncing the selected spool with Octoprint. The result is that after printing, the usage is not deducted in the manager.
```

### Steps taken to reproduce

-Start a print with spool selected from Octofarm.
-Prints starts in Octoprint and observe the spool selection for tool0 stays at ---select spool--

### What did you expect to happen

The selected spool in Octoprint to be the same as the selected one in Octofarm.

### To avoid the problem I had to

Select the spool manually in Octoprint.

**Comment by NotExpectedYet** [comment]
Will close as this was reported working and couldn't reproduce personally. 

Feel free to re-log if the error re-occurs.
