### ISSUE TITLE
Docker CPU load after update extremely high

### ISSUE THREAD

**Issue by taker218** [OctoFarm/OctoFarm#1117]
### OctoFarm Version

latest 1.4

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

docker

### Operating System

debian

### Location of the problem

Server

### Description of the problem

```markdown
I just noticed that the cpu usage reported by docker (I check this on all my docker containers with nagios) is extremely high (60-70%) after I did the upgrade to the latest docker image (monolithic).

I limited the container to 1 cpu core and 2GB of RAM (which should be more then enough). The curious thing is that the cpu usage on the system page is at around 20-30% at most (spikes to around 40% sometimes).

I attached the current logdump and a screenshot from the dashboard and the output of the docker usage (via portainer webinterface).

One thing I also noticed: The task for checking for octoprint updates is constantly running (at least the webinterface shows it like this).
```

### Steps taken to reproduce

1. Update the docker image to the latest image and restartet the container
2. Let octofarm run for a while

### What did you expect to happen

Not so high CPU usage.

Here are the attachements:
Logdump:
[octofarm_dump-6-22-2022-4-39-34 PM.zip](https://github.com/OctoFarm/OctoFarm/files/8958697/octofarm_dump-6-22-2022-4-39-34.PM.zip)

Screenshot from the system tab:
![grafik](https://user-images.githubusercontent.com/15029277/175057947-c86ca517-8b0c-442e-bb1b-96e3288b1c61.png)

Screenshot from portainer:
![grafik](https://user-images.githubusercontent.com/15029277/175058092-a26b1578-9fcf-49b2-bfc3-c56066198643.png)

Processes running in the docker container:
![grafik](https://user-images.githubusercontent.com/15029277/175058330-bcaa777d-b684-4e24-8d8a-77a571a680e1.png)

### To avoid the problem I had to

After a restart the cpu usage is fairly low, but I don't want to restart the container every hour or so.

**Comment by NotExpectedYet** [comment]
> > I'll see if I can force build the dockers with the fix didn't realise they didn't build unless there's another update available for the container? Not sure how portainer works.
> 
> Portainer itself is just a web ui for docker and I find it really nice to use. Makes working with docker a lot easier
> 
> I just pulled the latest docker image and so far it seems like the cpu usage is down quite a bit (hovering between 7 and 10%) and docker reports a cpu usage of around 20-25%. I don't know where the difference is coming from, but this is looking a lot better now. I'll have an eye on the cpu usage the next time, but the client is now on .15 (which I assume is the latest version)

Yeah you have power plugins on yours if I remember rightly. Gather it was that and the usage was increasing from visiting one of the views abut thank you for the report back! Should lower a lot more when I do the next push to make it a server side task. 

> 
> > Regarding the task for updates do you mean the circle loader keeps spinning or the last run time keeps incrementing? The task doesn't run until 24 hours after boot and only 24 hours after that so once a day. The spinner is just there as it's waiting for it to run.
> 
> that makes sense, since I just restarted the container the task will run tomorrow, got it!

Yeah I'll change that icon as it's not very alluding to what's going on.

**Comment by NotExpectedYet** [comment]
The next push will move all the calls server side as mentioned so it "should" reduce stuff back to normal CPU usages. 

I've created a new task that will check for the power state every 30 seconds. It will close this issue but feel free to log another if it persists. Hopefully it's licked. 

Just to mention the last release with the proxies, it is expected to increase the CPU usage a bit but yeah not as much as you saw aha. Cheers for the reports as always.
