### ISSUE TITLE
Job History - cost & usage sort order greyed out

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1138]
### OctoFarm Version

1.4.3

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Web Interface

### Description of the problem

```markdown
All the filters on the History tab work for the job history listed below, 
But cost and usage sort are greyed out, despite jobs having filament and cost values.
```

### Steps taken to reproduce

1. Print some things
2. Navigate to the History tab
![Screenshot 2022-06-24 205300](https://user-images.githubusercontent.com/95956617/175539893-7c6c7013-3369-4267-83e2-c239fd2dd939.png)

### What did you expect to happen

The filter to be selectable and sort by it.

**Comment by NotExpectedYet** [comment]
I'm going to remove these options for now, I will add them back in for the new UI reboot.
