### ISSUE TITLE
Printer Job Status - User Printing doesn't match job history (OP User)

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1144]
### OctoFarm Version

1.5.0

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.0.4.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Web Interface

### Description of the problem

```markdown
On the Job window, "User Printing" lists no user registered which doesn't match the job history tab when print is initiated by OP user.
```

### Steps taken to reproduce

1. print something with OP
2. look at the job tab

![Screenshot 2022-06-26 150327](https://user-images.githubusercontent.com/95956617/175803382-660442ab-633c-4a6b-bc70-d4fed9c59598.png)

### What did you expect to happen

The User printing to list the OP user which will be put into the job history entry.

**Comment by NotExpectedYet** [comment]
User printing is the OctoFarm user not the OctoPrint user so it's not suppose to be there if you run a print from OctoPrint. 

Could be a fall back I suppose. 

My grand visions for that feature is to eventually allow for a admin to "lock" a printer from anyone else touching it whilst someone else is printing. This obv... wouldn't work in a situation where OctoPrint initiates the print as OctoFarm would have no knowledge of it's user. There's no issue adding a fallback for display purposes though. That feature would be irrelevant for anyone firing straight from the slicer.
