### ISSUE TITLE
Receiving a TypeError on all of the printer views

### ISSUE THREAD

**Issue by brooksware2000** [OctoFarm/OctoFarm#1147]
### OctoFarm Version

1.5.0

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu Server on Raspberry Pi 4

### Location of the problem

Web Interface

### Description of the problem

```markdown
Whenever I go to any of the printer views (Panel, List, Camera, Group, Superlist, Current Operations), I receive the following pop-up error:

TypeError ERROR (undefined):
Please report this error to OctoFarm Issues!
Cannot read properties of undefined (reading 'operations')
FILE INFO
LINE: undefined
COL: undefined
STACK:
TypeError: Cannot read properties of undefined (reading 'operations') at http://192.168.1.118:4000/assets/dist/combined-view.runner.min.js?1.5.0:2:855567
```

### Steps taken to reproduce

1.  Click on any of the printer views (Panel, List, Camera, Group, Superlist, Current Operations).

### What did you expect to happen

N/a

### To avoid the problem I had to

N/a

**Comment by brooksware2000** [comment]
Here is a screenshot and logfiles:
[OctoFarm.Printer.OctoPrint2.log](https://github.com/OctoFarm/OctoFarm/files/8986833/OctoFarm.Printer.OctoPrint2.log)
![Screenshot 2022-06-26 073634](https://user-images.githubusercontent.com/568233/175819601-bae01953-9d6d-48b4-b3fb-8ba0223f106c.png)

**Comment by NotExpectedYet** [comment]
Is this a fresh install?

**Comment by NotExpectedYet** [comment]
Try saving your client settings see if it resolves.

**Comment by brooksware2000** [comment]
> 

No, I ran the internal upate.

**Comment by brooksware2000** [comment]
> Try saving your client settings see if it resolves.

No dice here either.

**Comment by NotExpectedYet** [comment]
Can you check what client version you have please?

**Comment by brooksware2000** [comment]
Client version is 1.5.0

**Comment by NotExpectedYet** [comment]
Weird, it's something server side by the looks as it's the current operations data. 

Would you mind generating a log dump for me please? It will have all the logs in it as there won't be anything in the printer data one. 

System -> Logs -> Log Dump

**Comment by NotExpectedYet** [comment]
Would you also mind trying to clear your cache as well? It shouldn't be needed but that file referring to the "operations" key is really old which is why I'm confused as it's handled by the event.js file, not any of those view files, it's not even imported. So think it might be the browser not updating a file correctly. 

I'll work in some better cache busting system for the next version as it's currently only appending `?1.5.0` to the urls which isn't very robust.

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/175901298-293b4799-74a9-4651-a52e-7f7387697330.png)

Found it, I wasn't using the cache at all for this file. Should resolve when you clear cache, and next version will not require it.
