### ISSUE TITLE
Quick Connect Error (when serial not ready)

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1151]
### OctoFarm Version

1.5.0

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Web Interface

### Description of the problem

```markdown
When pressing quick connect, OF powers the plug attempts the connection, but flags an error if the printer serial isn't ready in time.

If OP is set to auto connect the serial from the power plugs plugin after a certain amount of time, the issue error is irrelevant as the connection is retried.

Customisable options for quick connection would solve this, either:
An adjustable connection delay per printer (equivalent function to the OP plugin)
or
Option to disable the serial connection portion of the quick connect function and allow the process to be handled only by the OP power plugin
```

### Steps taken to reproduce

1. power a printer with a slow post

### What did you expect to happen

.

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/176173133-490c16ba-231b-42f3-a4a6-8eeb87f08870.png)

Guess you'll make me fix some todo's ahaha
