### ISSUE TITLE
Spool remains locked after printer removed

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1155]
### OctoFarm Version

1.5.1

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Server

### Description of the problem

```markdown
The spool remains locked when assigned to a deleted printer.
Spool Manager lists the tab as not assigned and its assumed its available for use.
```

### Steps taken to reproduce

1. Assign a spool to a printer
2. Delete the printer from the printers menu
3. Try assign the spool to another printer from a view (eg panel)
![Screenshot 2022-06-30 191707](https://user-images.githubusercontent.com/95956617/176664631-5fa797ce-5427-4397-b438-1c3ba59a1dd5.png)

4. Spool shows as locked/in use
5. Navigate to Spool manager in Filament tab and locate spool
6. Spool lists as "not assigned"
![Screenshot 2022-06-30 191740](https://user-images.githubusercontent.com/95956617/176664730-2a83da54-7cd2-4f41-93bc-27c2704c2120.png)

### What did you expect to happen

The spool to be available for selection on the panel screen

### To avoid the problem I had to

Edit the spool (in spool manager) and press save again.

**Comment by NotExpectedYet** [comment]
Can you force it un-assigned? Click edit and save, it "should" unassign it again. 

Yeah that needs sorting. Gather it's not unassigning attached spools on delete.
