### ISSUE TITLE
OctoFarm stops syncing/updating printer state randomly

### ISSUE THREAD

**Issue by Lochte** [OctoFarm/OctoFarm#1163]
### OctoFarm Version

1.4.3

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Linux 5.4.0-109-generic

### OctoPrint Plugins

bed visualizer, M73 progress

### Location of the problem

Not sure

### Description of the problem

```markdown
At times it seems that OctoFarm stops syncing with the printers. In this case the printer reported 'Complete' while it was printing. I've tried this several times before.
```

### Steps taken to reproduce

1. Use Octofarm a lot. 
2. wait for this bug to happen

### What did you expect to happen

Expected Octofarm to keep syncing the printer states while both printers and Octofarm runs actively.

### To avoid the problem I had to

Reconnect the sockets. This keeps the syncing alive for some time. 

Pre re-connecting the sockets: 
![Screenshot from 2022-07-13 12-16-47](https://user-images.githubusercontent.com/15735262/178713191-998ead10-18fe-42ff-a8ed-dd6033465d18.png)

Post re-connecting the sockets:
![Screenshot from 2022-07-13 12-18-01](https://user-images.githubusercontent.com/15735262/178713210-3cdfd448-e9a1-4cce-822c-697594e24117.png)

**Comment by NotExpectedYet** [comment]
Not entirely sure but I think OctoFarm is missing a websocket issue somewhere.

**Comment by NotExpectedYet** [comment]
Hello, would you mind uploading the logs you have please?

**Comment by NotExpectedYet** [comment]
Could you also try the latest release and see if it's any better?

**Comment by Lochte** [comment]
Logs: 
[octofarm_dump-8-8-2022-7-27-13 AM.zip](https://github.com/OctoFarm/OctoFarm/files/9279717/octofarm_dump-8-8-2022-7-27-13.AM.zip)

Will try to update and get back in a few days regarding the issue.

**Comment by NotExpectedYet** [comment]
Brilliant thanks. I made some tweaks in further versions but logs will help

**Comment by NotExpectedYet** [comment]
I use to get the issue at work quite a lot but it hasn't materialised in a bit so hopefully will be able to track it down.

**Comment by Lochte** [comment]
Hi James, 

This issue is still there.. I experienced it once last week and just now. First time was following a few manual inputs from the LCD screen (aborting print and messing with extruder temperatures). Now five printers was started following an inactive weekend. Screendump shows statuses after initiating five printers: 
![Screenshot from 2022-08-15 11-01-52](https://user-images.githubusercontent.com/15735262/184607829-a19265a2-37d5-4bae-a373-caac109a14f3.png)
Statuses after reconnecting all sockets: 
![Screenshot from 2022-08-15 11-02-51](https://user-images.githubusercontent.com/15735262/184607872-9926fc20-fb22-4786-8e50-a9e281b6dc76.png)

New logs: 
[octofarm_dump-8-15-2022-9-03-01 AM.zip](https://github.com/OctoFarm/OctoFarm/files/9336198/octofarm_dump-8-15-2022-9-03-01.AM.zip)

**Comment by NotExpectedYet** [comment]
Thanks for the additional info. Hopefully I can see it in the logs. Do you have a round about time when they lost connection? If it's between days that's fine. 

I don't think it's related to the tinkering on the printer screen. It's kind of like there's a weird state the socket ends up in and Im disconnecting rather than reconnecting.

**Comment by Lochte** [comment]
The 'Voron 2' lost connection the 10th of august just before 16.00. The following screenshot shows: 
![Screenshot from 2022-08-10 15-57-06](https://user-images.githubusercontent.com/15735262/184909291-e18c75a5-30e5-4caf-ad7c-4a998218fea6.png)

I'm not sure about the other ones. But between Friday 12th and monday 15th.

**Comment by NotExpectedYet** [comment]
Thanks, I'm going to be doing some more work on OctoFarm this weekend so I'll take a look into it then. The times help loads, i have a starting point to work back from. 

What's your network like? Is it all WiFi? I double checked at work (all ethernet) and I haven't had this issue in a fair while by the looks, think that's still on 1.4.2 version. If it's WiFi I can setup a test pi here and see what happens with the odd drop.

**Comment by Lochte** [comment]
All printers are connected via ethernet. OctoFarm (now version 1.6.5) runs on a virtual server.

**Comment by NotExpectedYet** [comment]
Wondering if you've any idea what the below is? On the 10th of august there was a spurious set of requests made to the OctoFarm server for these. 

```
10/08/2022, 08:24:05 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: TRACE /Nessus41097765.html 404 160 - 2.122 ms
 
10/08/2022, 08:24:09 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: SEARCH / 404 142 - 2.896 ms
 
10/08/2022, 08:24:09 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: OPTIONS * 500 1066 - 1.775 ms
 
10/08/2022, 08:24:09 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: PROPFIND / 404 144 - 0.961 ms
 
10/08/2022, 08:24:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%80../%80../%80../%80../%80../%80../windows/win.ini 400 1066 - 3.116 ms
 
10/08/2022, 08:24:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%80../%80../%80../%80../%80../%80../winnt/win.ini 400 1064 - 3.726 ms
 
10/08/2022, 08:24:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%c0.%c0./%c0.%c0./%c0.%c0./%c0.%c0./%c0.%c0./windows/win.ini 400 1075 - 1.912 ms
 
10/08/2022, 08:24:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%c0.%c0./%c0.%c0./%c0.%c0./%c0.%c0./%c0.%c0./winnt/win.ini 400 1073 - 5.782 ms
 
10/08/2022, 08:24:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/windows/win.ini 400 1082 - 3.360 ms
 
10/08/2022, 08:24:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/winnt/win.ini 400 1080 - 3.144 ms
 
10/08/2022, 08:24:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/windows/win.ini 400 1186 - 3.568 ms
 
10/08/2022, 08:24:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/winnt/win.ini 400 1184 - 2.464 ms
 
10/08/2022, 08:24:12 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/etc/passwd 400 1181 - 2.546 ms
 
10/08/2022, 08:24:13 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST / 404 140 - 1.058 ms
 
10/08/2022, 08:24:14 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /index.php?s=xxxx 404 149 - 0.939 ms
 
10/08/2022, 08:24:14 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /webui/apps/sdcss 404 156 - 3.782 ms
 
10/08/2022, 08:24:14 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /av-centerd 404 150 - 1.343 ms
 
10/08/2022, 08:24:15 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /sawmillcl.exe 404 153 - 1.109 ms
 
10/08/2022, 08:24:15 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /sawmill6cl.exe 404 154 - 1.556 ms
 
10/08/2022, 08:24:15 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST / 404 140 - 1.588 ms
 
10/08/2022, 08:24:18 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /perl/ 404 145 - 1.323 ms
 
10/08/2022, 08:24:19 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /servlet/GetProductVersion 404 165 - 0.854 ms
 
10/08/2022, 08:24:19 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /servlet/GetProductVersion 404 165 - 0.623 ms
 
10/08/2022, 08:24:19 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /servlet/GetProductVersion 404 165 - 0.725 ms
 
10/08/2022, 08:24:19 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /servlet/GetProductVersion 404 165 - 0.627 ms
 
10/08/2022, 08:24:19 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /servlet/GetProductVersion 404 165 - 0.658 ms
 
10/08/2022, 08:24:19 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /servlet/GetProductVersion 404 165 - 0.780 ms
 
10/08/2022, 08:24:19 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /servlet/GetProductVersion 404 165 - 0.607 ms
 
10/08/2022, 08:24:20 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /jsonrpc 404 147 - 0.790 ms
 
10/08/2022, 08:24:20 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /server/service/smsConfigServiceHttpInvoker 404 182 - 0.966 ms
 
10/08/2022, 08:24:25 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: PRI * 500 1066 - 0.692 ms
 
10/08/2022, 08:24:32 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /spipe?Source=nessus 404 145 - 0.656 ms
 
10/08/2022, 08:24:33 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /cgi-bin/mainfunction.cgi 404 164 - 0.846 ms
 
10/08/2022, 08:24:33 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: OPTIONS * 500 1066 - 0.756 ms
 
10/08/2022, 08:24:37 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: GET /%NETHOOD%/ 400 1025 - 1.005 ms
 
10/08/2022, 08:25:09 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /flex2gateway/http 404 157 - 0.741 ms
 
10/08/2022, 08:25:09 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /messagebroker/http 404 158 - 1.435 ms
 
10/08/2022, 08:25:09 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /blazeds/messagebroker/http 404 166 - 1.351 ms
 
10/08/2022, 08:25:09 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /lcds/messagebroker/http 404 163 - 1.305 ms
 
10/08/2022, 08:25:09 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST / 404 140 - 1.150 ms
 
10/08/2022, 08:25:10 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /%70%68%70%70%61%74%68/%70%68%70?%2d%64+%61%6c%6c%6f%77%5f%75%72%6c%5f%69%6e%63%6c%75%64%65%3d%6f%6e+%2d%64+%73%61%66%65%5f%6d%6f%64%65%3d%6f%66%66+%2d%64+%73%75%68%6f%73%69%6e%2e%73%69%6d%75%6c%61%74%69%6f%6e%3d%6f%6e+%2d%64+%64%69%73%61%62%6c%65%5f%66%75%6e%63%74%69%6f%6e%73%3d%22%22+%2d%64+%6f%70%65%6e%5f%62%61%73%65%64%69%72%3d%6e%6f%6e%65+%2d%64+%61%75%74%6f%5f%70%72%65%70%65%6e%64%5f%66%69%6c%65%3d%70%68%70%3a%2f%2f%69%6e%70%75%74+%2d%6e 404 171 - 0.819 ms
 
10/08/2022, 08:25:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /FormHandler.cgi 404 155 - 1.077 ms
 
10/08/2022, 08:25:11 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST http://127.0.0.1/iControl/iControlPortal.cgi 404 167 - 0.856 ms
 
10/08/2022, 08:25:14 | HTTP | Middleware-Morgan 
 HTTP MESSAGE: POST /cgi-bin/file_transfer.cgi 404 165 - 0.876 ms
```

I believe I've actually tracked down the issue though. Seems the websocket connection went stale on 11th and attempted to passive login without any details. 

```
 HTTP MESSAGE: Passive login failed...FetchError: request to http://10.10.210.23/api/login?passive=true failed, reason: connect EHOSTUNREACH 10.10.210.23:80 
```

Is that your Voron IP by anychance?

**Comment by NotExpectedYet** [comment]
Yep found it, this issue will close when I push the fix but please do re-open if it hasn't.
