### ISSUE TITLE
Text colour "Printing from SD" unreadable on File Manager

### ISSUE THREAD

**Issue by IHVD** [OctoFarm/OctoFarm#1164]
### OctoFarm Version

1.5.1

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

FarmPi

### Location of the problem

Web Interface

### Description of the problem

```markdown
The Text Colour of "Printing from SD" on both File Manager /filemanager and Printers /printers is Black. On /printers you can read it better since the background colour is Yellowy-Orange, but on /filemanager the background is the same colour as Operational, so you can't read the black "Printing from SD" text.
```

### Steps taken to reproduce

1. Print from an SD Card on your OctoPrint-enabled Printers
2. Navigate to /printers and read the Printer State of said printer

### What did you expect to happen

The text to be a readable white, and maybe the /filemanager state to also be orange?

**Comment by NotExpectedYet** [comment]
Hu they use the same colour state file so not sure why it's orange on one and black on another screen they should display the same. 

I don't currently account for this state at all though so I'll add it for the next release.
