### ISSUE TITLE
File Manager - TypeError: t.currentProfile is undefined

### ISSUE THREAD

**Issue by Aron3DP** [OctoFarm/OctoFarm#1165]
### OctoFarm Version

1.5.1

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu

### Location of the problem

Server

### Description of the problem

```markdown
File Manager not displaying Printers.

Getting ...
OctoFarm Error ERROR (999):
FILE INFO
LINE: 2
COL: 609428
FILE:
http://10.10.2.170:4000/assets/dist/file-manager.runner.1.5.1.min.js
STACK:
n@http://10.10.2.170:4000/assets/dist/file-manager.runner.1.5.1.min.js:2:609428 @http://10.10.2.170:4000/assets/dist/file-manager.runner.1.5.1.min.js:2:711761 

I can however access the files from the Panel view individually with each printer. Currently running three.
```

### Steps taken to reproduce

Clicking on the File Manager Tab

### What did you expect to happen

Display each Printer with re-sync controls

**Comment by AronsPC** [comment]
Which log file specifically would I need to upload?

**Comment by NotExpectedYet** [comment]
> Which log file specifically would I need to upload?

You can do a log dump on System -> Logs -> Log Dump. It will generate a .zip file with everything I should need. 

Think it's related to this #1102

**Comment by AronsPC** [comment]
[octofarm_dump-7-16-2022-8-03-16 AM.zip](https://github.com/OctoFarm/OctoFarm/files/9125689/octofarm_dump-7-16-2022-8-03-16.AM.zip)
Here it is. Thanks. I generated the error message again just before downloading it.

**Comment by AronsPC** [comment]
Awhile back I was getting a similar error with the Spool Manager but it went away. The last effort attempt I was going to do was a fresh install in a new VM and try and transfer over all my information.

**Comment by NotExpectedYet** [comment]
That's perfect thanks. 

Will take a look through. 

It's to do with the profile not scanning. Another user reported that after boot, opening the Printers -> Manage -> Settings use to trigger the data back.

**Comment by AronsPC** [comment]
That work around did the trick just now. I remember finding something similar with the Spool Manager before as well. If I went to the printer directly it would let it re-appear.

**Comment by NotExpectedYet** [comment]
I'm hoping this will be solved in the next version as I've re-written the onboarding logic for a printer.
