### ISSUE TITLE
Type error when powering printer on via file manager.

### ISSUE THREAD

**Issue by KKriz** [OctoFarm/OctoFarm#1168]
### OctoFarm Version

1.5.1

### OctoPrint Version(s)

latest

### pm2 or docker?

docker

### Operating System

Unraid

### Location of the problem

Web Interface

### Description of the problem

```markdown
Getting a typeError when powering up the printer with the start button from the file manager.
```

### Steps taken to reproduce

Pressing start button to power up printer through PSU control.

### What did you expect to happen

No typeError message.

**Comment by NotExpectedYet** [comment]
Will be fixed in next version :) thank you for the report!
