### ISSUE TITLE
Filament not syncing after print finishes

### ISSUE THREAD

**Issue by taker218** [OctoFarm/OctoFarm#1169]
### OctoFarm Version

1.5.1

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

docker

### Operating System

Debian

### OctoPrint Plugins

filament manager (1.9.1)

### Location of the problem

Web Interface

### Description of the problem

```markdown
It seems like the filament manager is not syncing the spools after a print is finished.
I need to resync the filament manually to see the remaining filament on the spool.
```

### Steps taken to reproduce

1. Start a print and wait for it to finish
2. Have a look at the filament weight shown in the filament manger in OctoFarm and OctoPrint to see that it doesn't match

### What did you expect to happen

The weight to be synced after a print

### To avoid the problem I had to

Sync the filament manually via the "Re-Sync Spools/Profiles" button on the webinterface

Here's the log dump, if that might help.
[octofarm_dump-7-20-2022-4-01-46 PM.zip](https://github.com/OctoFarm/OctoFarm/files/9150478/octofarm_dump-7-20-2022-4-01-46.PM.zip)

**Comment by NotExpectedYet** [comment]
I can see it making the call but it's responding with a 404 on the individual spool but that should only effect the history record not the filament manager as that's updated from the full resync that's fired afterwards. 

Cheers for the report seems this has been like this for a while. I'll get both sorted for next release.

**Comment by NotExpectedYet** [comment]
I can see it making the call but it's responding with a 404 on the individual spool but that should only effect the history record not the filament manager as that's updated from the full resync that's fired afterwards. 

Cheers for the report seems this has been like this for a while. I'll get both sorted for next release.
