### ISSUE TITLE
Type Error - document.getElementById isnull

### ISSUE THREAD

**Issue by francaflavio** [OctoFarm/OctoFarm#1172]
### OctoFarm Version

1.4.3

### OctoPrint Version(s)

18.1

### pm2 or docker?

Running under docker (dockerfile)
Running under pm2

### Operating System

octopi 0.18.0

### OctoPrint Plugins

octotext

### Location of the problem

Web Interface

### Description of the problem

```markdown
Type Error - document.getElementById isnull

When I add a new Administrator user, and try login
the first screen is this error.

If I use the first user created no problem occur.
```

### Steps taken to reproduce

1. create new user Administrator
2. login with the new user 

### What did you expect to happen

Show normal interface

### To avoid the problem I had to

Close popup but in other menus occur also error and doesn't show the interface, only json code.

<a href='https://postimg.cc/BPT3cwGc' target='_blank'><img src='https://i.postimg.cc/BPT3cwGc/Captura-de-Tela-26.png' border='0' alt='Captura-de-Tela-26'/></a>

**Comment by NotExpectedYet** [comment]
Found it, client settings are not generated on new administrator user creation... wow... 

Will be fixed for the next version.
