### ISSUE TITLE
Can't update printer name

### ISSUE THREAD

**Issue by taker218** [OctoFarm/OctoFarm#1176]
### OctoFarm Version

1.6

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

docker

### Operating System

Debian

### Location of the problem

Web Interface

### Description of the problem

```markdown
I just updated to the newest docker image and after the start all printers where named "undefined" and I had an error regarding the api. On one printer the API key was wrong (don't know why, it worked just fine before the update).

I wanted to change the names of the printers to the correct ones again, but it always went back to "undefined".
I tried to generate a printer name and saved this, this worked without a problem, but now I can't seem to update the printer names anymore.

Regarding the API key it worked after I changed the API key to another one from this printer and back to the one for octofarm.
```

### Steps taken to reproduce

1. Update to current docker image
2. Go to printer page and try to change a printer name

### What did you expect to happen

That the printer name would happen

### To avoid the problem I had to

Here's the log dump from just now:
[octofarm_dump-8-6-2022-10-19-47 PM.zip](https://github.com/OctoFarm/OctoFarm/files/9275716/octofarm_dump-8-6-2022-10-19-47.PM.zip)
Hope this helps with the naming problem and maybe also with the api key stuff.

**Comment by NotExpectedYet** [comment]
Should be fixed shortly. 

Sorry about that. 

Not sure regarding the API key as nothing has touched that for a long while. There we're changes on the name though. Do let me know if the API issue happens again.
