### ISSUE TITLE
"API Scan has issues!" - False Alert

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1178]
### OctoFarm Version

1.6.0

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.2 LTS

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Not sure

### Description of the problem

```markdown
Likely related to #1102

After upgrading from 1.5.1 a new 'error' has appeared in the Alerts column, without any configurtion changes.

Mouse over reports "No issue from scanning OctoPrints API", yet the warning icon is listed and recent alerts lists "API Scan has issues!"
```

### Steps taken to reproduce

![Screenshot 2022-08-07 080633](https://user-images.githubusercontent.com/95956617/183270262-17f385a4-4afa-4f4f-be41-098693a81186.png)

1. Upgrade to 1.6.0
2. Login to the UI

Also reoccurs if you've cleared them and reboot the server.
1. Clear the issue by going into settings on each one
2. Restart OF
3. Login to the UI

### What did you expect to happen

N/A

### To avoid the problem I had to

Pressing Manage > Settings, then backing out clears the error (with no configuration changes). And the last status updates to "Acquired settings data".

![Screenshot 2022-08-07 080659](https://user-images.githubusercontent.com/95956617/183270230-8e5b8cff-ee7d-41c8-af05-b21b80f9a8ea.png)

![Screenshot 2022-08-07 080718](https://user-images.githubusercontent.com/95956617/183270224-f275b021-1e5d-4443-9ab0-8324d6b62783.png)

[octofarm_dump-8-7-2022-12-04-01 AM.zip](https://github.com/OctoFarm/OctoFarm/files/9275966/octofarm_dump-8-7-2022-12-04-01.AM.zip)

**Comment by NotExpectedYet** [comment]
Think this should also clear up once I fix the names
