### ISSUE TITLE
Print job listed in current operations when powering on.

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1179]
### OctoFarm Version

1.6.0

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.2 LTS

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Not sure

### Description of the problem

```markdown
When you quick connect a printer with power on function, a blank print job is listed in the current operations bar.
```

### Steps taken to reproduce

1. Turn on printer via quick connect button

![Screenshot 2022-08-07 082318](https://user-images.githubusercontent.com/95956617/183270378-4eef8bd6-1079-42ae-841c-cf011bb07d2b.png)

### What did you expect to happen

Either
A - nothing to appear (if this is a bug)
B - the operation to list "printername is powering on" with no file or time estimate lines (if this is added as an improvement).

**Comment by NotExpectedYet** [comment]
Huh that's a new one, I can only gather it's related to the missing printer name issue.
