### ISSUE TITLE
Cannot read properties of undefined (reading 'historyByDay')

### ISSUE THREAD

**Issue by delring** [OctoFarm/OctoFarm#1193]
### OctoFarm Version

1.6.5

### OctoPrint Version(s)

1.8.2

### pm2 or docker?

docker

### Operating System

Unraid/Linux

### OctoPrint Plugins

BLTouch Plugin (0.3.4), Filament Manager (1.9.1), FileManager (0.1.6), Resource Monitor (0.3.6)

### Location of the problem

Web Interface

### Description of the problem

```markdown
Logging in, dashboard loading. This error pops up:
TypeError ERROR (undefined):
Please report this error to OctoFarm Issues!
Cannot read properties of undefined (reading 'historyByDay')
FILE INFO
LINE: undefined
COL: undefined
STACK:
TypeError: Cannot read properties of undefined (reading 'historyByDay') at http://192.168.0.1:4000/assets/dist/dashboard.runner.1.6.5.min.js:2:36028 at async http://192.168.0.1:4000/assets/dist/dashboard.runner.1.6.5.min.js:2:35925

Expected dashboard to load with no errors.
```

### Steps taken to reproduce

Logging in, dashboard loading.

### What did you expect to happen

Expected dashboard to load with no errors.

### To avoid the problem I had to

Close the window. Usually, I have to log in again. Then the dash loads with no issues.
[octofarm_dump-9-1-2022-4-56-34 PM.zip](https://github.com/OctoFarm/OctoFarm/files/9473339/octofarm_dump-9-1-2022-4-56-34.PM.zip)

**Comment by NotExpectedYet** [comment]
Cheers for the report. 

Think this is something to do with the client compilation changes and I've been unable to reproduce locally. Will get it sorted.
