### ISSUE TITLE
Not able to create folders - "Sorry your folder couldn't be saved"

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#1226]
### Discussed in https://github.com/OctoFarm/OctoFarm/discussions/1225

<div type='discussions-op-text'>

<sup>Originally posted by **rajavel1990** September 25, 2022</sup>
I have installed the latest version 1.6.8 on my windows machine and i am not able to create folders for each of the printers. I get "Sorry your folder couldn't be saved" error.
<img width="2048" alt="Screenshot 2022-09-24 at 8 38 20 PM" src="https://user-images.githubusercontent.com/43663845/192135912-877d716c-f3c2-4aec-809a-f5fb7e8140af.png">
</div>

**Comment by Firefighter1023** [comment]
Confirmed same on my server, was present in 1.6.5.  API and CORS is set correctly.

**Comment by NotExpectedYet** [comment]
This is weird as I'm getting unauthorized on my local version when creating a folder. 

Seems like it's OP sending that back, as my requests haven't changed. Just trying to narrow it down now.
