### ISSUE TITLE
Under ListView, machines are randomly showing "No File Selected" under CurrentFile Column

### ISSUE THREAD

**Issue by Firefighter1023** [OctoFarm/OctoFarm#1227]
### OctoFarm Version

1.6.8

### OctoPrint Version(s)

1.8.2

### pm2 or docker?

pm2

### Operating System

Debian/FarmPi

### Description of the problem

When printers are working or in standby status the result is the same.  Viewing the "list" view results in each of the printers randomly displaying the correct current file, or more often "No File Selected" in the current file column.  

The top ribbon under current operations displays all correct information.

### Steps taken to reproduce

Install OctoFarm 1.6.8
Connect many mutiple printers via OctoPi
All current file fields will mostly not populate or populate randomly
Refreshing the page multiple times results in random displays of the same information
Reconnecting all sockets, rebooting server, refreshing page all have no impact on the other fields

[octofarm_dump-9-25-2022-10-40-48 AM.zip](https://github.com/OctoFarm/OctoFarm/files/9640996/octofarm_dump-9-25-2022-10-40-48.AM.zip)

**Comment by swindmiller** [comment]
I noticed this too on 1.6.5, just updated to 1.6.8 and Current Operation showed I had a printer printing. List view showed Complete for the printer with no file loaded. Refreshed the page and it now showed Printing with a progress but still showed No File Selected. A few minutes later I returned to the tab (didn't close it) and it showed everything correct. Hopefully this help troubleshoot it. 
Scott

**Comment by NotExpectedYet** [comment]
What browsers are you both using?

**Comment by NotExpectedYet** [comment]
Also Is there any sorting applied on the page? Or filtering? 

Again I can't reproduce this with 30 printers been drawn on list view so I gather something is different here. I returned back to the old drawing method before 1.6.5 as well. The only thing that remains is checking if a printer is in view on the page before updating it. 

I tested Firefox and Firefox developer edition and chrome developer edition and they were working fine with the implementation on my Linux box.

**Comment by NotExpectedYet** [comment]
Let me know anyway I'll try get to it again this week.

**Comment by Firefighter1023** [comment]
> What browsers are you both using?

Tested in Chrome and IE on windows, Safari on IOS; I will check Firefox on Linux when I have a moment.

**Comment by Firefighter1023** [comment]
Same result in firefox.

**Comment by NotExpectedYet** [comment]
How strange. Cheers for trying those. I'll double check it's sounding like this is the in view detection so I will disable it over weekend until I can make sure it's working on more than just my browsers.

**Comment by NotExpectedYet** [comment]
Huh, I disabled the inviewport check last update... what the hell is going on here then.

**Comment by NotExpectedYet** [comment]
Think I've actually found the issue! woop

**Comment by NotExpectedYet** [comment]
Wow that was annoying. 

If anyone wants a work around until I get this next version released, then disable "Current Operations" on the view it's on.
