### ISSUE TITLE
Unable to update Wallpaper

### ISSUE THREAD

**Issue by cuesir** [OctoFarm/OctoFarm#1234]
### OctoFarm Version

1.6.8

### OctoPrint Version(s)

1.8.3

### pm2 or docker?

pm2

### Operating System

Windows 10

### Description of the problem

Unable to change wallpaper

### Steps taken to reproduce

1. Selected .jpg
2. Clicked upload
3. page refreshes and nothing happens.
4. restarted octofarm and wallpaper still not updated.
5. replaced the default_bg.jpg file to the file I want and still not changed.

**Comment by NotExpectedYet** [comment]
I believe your old wallpaper should come back when I've fixed this. 

I gather history view is broken too
