### ISSUE TITLE
Boot error on Raspberry Pi 4 Model B 4GB - start4.elf: is not compatible

### ISSUE THREAD

**Issue by dirkvranckaert** [OctoFarm/OctoFarm#1319]
### OctoFarm Version

1.7.3

### OctoPrint Version(s)

n/a

### pm2 or docker?

pm2

### Operating System

Raspberry Pi 4 Model B

### Description of the problem

I followed instructions on installing (flashing) the image on my Raspberry Pi 4 Model B.
However on boot errors are being displayed (causing boot to be aborted).

The error is:
```shell
start4.elf: is not compatible
This board requires newer software
```
Screenshot:  ![IMG_1132](https://user-images.githubusercontent.com/4660794/196119056-2d3c98df-4913-4f34-9f8d-175b81046d43.jpg)

### Steps taken to reproduce

Follow installation on wiki

**Comment by NotExpectedYet** [comment]
This isn't an OctoFarm bug, you'll need to report it to the FarmPi repo.

**Comment by NotExpectedYet** [comment]
https://github.com/mkevenaar/FarmPi
