### ISSUE TITLE
OctoFarm not running

### ISSUE THREAD

**Issue by GreenGuy53** [OctoFarm/OctoFarm#1322]
### OctoFarm Version

1.2

### OctoPrint Version(s)

1.5.3

### pm2 or docker?

pm2

### Operating System

Raspberry pi

### Description of the problem

I was able to set up the OctoFarm and find it by typing in the ip address into a browser. It then says The OctoFarm is not running and no matter what I do will not fix it. I can't see how this being run a school run wifi would break it but I'm not sure. As far as I know everything is up to date, it's a rasp pi 4 with 2 g, and I'm running ethernet to it. Please help

### Steps taken to reproduce

1. Downloaded farm pi image
2. Unzipped the folder
3. Flashed it to micro SD card with rasp pi software
4. Plugged it in to rasp pi 4
5. Logged into Ubuntu/farmpi
6. Typed ip address web browser 
7. Found it wasn't connecting
8. Also find I can't/dont know how to pull up error logs

**Comment by NotExpectedYet** [comment]
1.2 is an very old version... It's not supported. 

FarmPi isn't my image either so I don't support it. 

You'll have to ask at his GitHub, or install through the normal method so I can help. 

https://github.com/mkevenaar/FarmPi

**Comment by NotExpectedYet** [comment]
I'll close as this doesn't sound like an issue with OctoFarm. 

But I am happy to help troubleshoot non FarmPi installation methods.

**Comment by NotExpectedYet** [comment]
I think I've had a few users reporting issues with flashing Pi4 and other stuff. 

Personally my recommendation is to just install it through the cli with the Ubuntu image. The commands should all be copy and paste. 

Just make sure it's a 20.04 image but I think the others should be fine.

**Comment by GreenGuy53** [comment]
I would love even the smallest amount of help as I am so incredibly clueless when it comes to things like this, where can I find the copy and paste commands.

**Comment by NotExpectedYet** [comment]
I'll outline the steps below for you. If anything's confusing just let me know and I'll try and explain it better :) 

So basically you'll need to flash a 64-bit raspberry pi image due to the database requirements my application uses. 

Use whatever method you did before but just use this image: 
https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04.1&architecture=server-arm64+raspi

Then we need to gain access to the systems CLI as that doesn't have any desktop environment on it. 

If you've a keyboard and mouse attached you should just be able to login with the username: ubuntu and password: ubuntu. 

If not, then you'll have to find the ip address the device has been given similar to what you did with OctoPrint to access the interface. Then use a program called putty to connect to the system over SSH. To enable this on Ubuntu I think you need to put the SD card back into your pc and create a file called "ssh" with no extension on the main part of the drive. 

Once your logged in you should be able to follow the commands in this document, just by copy and pasting them in. 
https://docs.octofarm.net/installation/install-linux-ubuntu.html
Just be away that in the setup mongodb part, you can use the top 20.04 command and ignore the 18.04 and 16.04 versions. 

I'm hoping to simplify all this for v2.0 I just don't get all the time I'd like to put into making a binary out of this application currently.

**Comment by GreenGuy53** [comment]
Thanks a lot I'll try it later today.

**Comment by GreenGuy53** [comment]
The Pi keeps saying "This board requires newer software", do you know what I'm doing wrong?

**Comment by GreenGuy53** [comment]
> I'll outline the steps below for you. If anything's confusing just let me know and I'll try and explain it better :)
> 
> So basically you'll need to flash a 64-bit raspberry pi image due to the database requirements my application uses.
> 
> Use whatever method you did before but just use this image: https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04.1&architecture=server-arm64+raspi
> 
> Then we need to gain access to the systems CLI as that doesn't have any desktop environment on it.
> 
> If you've a keyboard and mouse attached you should just be able to login with the username: ubuntu and password: ubuntu.
> 
> If not, then you'll have to find the ip address the device has been given similar to what you did with OctoPrint to access the interface. Then use a program called putty to connect to the system over SSH. To enable this on Ubuntu I think you need to put the SD card back into your pc and create a file called "ssh" with no extension on the main part of the drive.
> 
> Once your logged in you should be able to follow the commands in this document, just by copy and pasting them in. https://docs.octofarm.net/installation/install-linux-ubuntu.html Just be away that in the setup mongodb part, you can use the top 20.04 command and ignore the 18.04 and 16.04 versions.
> 
> I'm hoping to simplify all this for v2.0 I just don't get all the time I'd like to put into making a binary out of this application currently.


The Pi keeps saying "This board requires newer software", do you know what I'm doing wrong?

**Comment by NotExpectedYet** [comment]
> > I'll outline the steps below for you. If anything's confusing just let me know and I'll try and explain it better :)
> > So basically you'll need to flash a 64-bit raspberry pi image due to the database requirements my application uses.
> > Use whatever method you did before but just use this image: https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04.1&architecture=server-arm64+raspi
> > Then we need to gain access to the systems CLI as that doesn't have any desktop environment on it.
> > If you've a keyboard and mouse attached you should just be able to login with the username: ubuntu and password: ubuntu.
> > If not, then you'll have to find the ip address the device has been given similar to what you did with OctoPrint to access the interface. Then use a program called putty to connect to the system over SSH. To enable this on Ubuntu I think you need to put the SD card back into your pc and create a file called "ssh" with no extension on the main part of the drive.
> > Once your logged in you should be able to follow the commands in this document, just by copy and pasting them in. https://docs.octofarm.net/installation/install-linux-ubuntu.html Just be away that in the setup mongodb part, you can use the top 20.04 command and ignore the 18.04 and 16.04 versions.
> > I'm hoping to simplify all this for v2.0 I just don't get all the time I'd like to put into making a binary out of this application currently.
> 
> The Pi keeps saying "This board requires newer software", do you know what I'm doing wrong?

Hmmm how new is the Pi? 

I've never seen that before personally.

**Comment by NotExpectedYet** [comment]
You might have to try the later 22.09 image. 

I think there's some issues with mongodb on that one though :/

**Comment by GreenGuy53** [comment]
The pi is to my knowledge as new as they come, its a raspberry pi 4 model B with 2 or 4 GB of ram (I've tried both models). I'm trying a different 20.04 image, if that doesn't work I'll try a 22.09 image, I'm assuming I'll have to do something differently as 22.09 is not in the copy and paste selection list on the OctoFarm site.

**Comment by NotExpectedYet** [comment]
> The pi is to my knowledge as new as they come, its a raspberry pi 4 model B with 2 or 4 GB of ram (I've tried both models). I'm trying a different 20.04 image, if that doesn't work I'll try a 22.09 image, I'm assuming I'll have to do something differently as 22.09 is not in the copy and paste selection list on the OctoFarm site.

The only thing that will be different is the Mongodb installation steps.

**Comment by NotExpectedYet** [comment]
Whoops sorry. On mobile. 

https://wiki.crowncloud.net/?How_to_Install_Latest_MongoDB_on_Ubuntu_22_04

It's 22.04 sorry not 09 but that should help

**Comment by GreenGuy53** [comment]
Thank you

**Comment by GreenGuy53** [comment]
Hey so after some more trying, we still have no clue, I can't even find a 22.09 image so I'm losing my mind here just banging my head against a wall on this problem.

**Comment by NotExpectedYet** [comment]
> Hey so after some more trying, we still have no clue, I can't even find a 22.09 image so I'm losing my mind here just banging my head against a wall on this problem.

If you look right above your thank you comment, there is a comment explaining I mean 22.04 not 22.09....

**Comment by NotExpectedYet** [comment]
Sorry if that wasn't clear enough, just re-read it back.
