### ISSUE TITLE
Fresh install failing to boot server

### ISSUE THREAD

**Issue by SavvyRainbow** [OctoFarm/OctoFarm#1329]
### OctoFarm Version

1.7.3

### OctoPrint Version(s)

N/A

### pm2 or docker?

docker

### Operating System

Ubuntu

### Description of the problem

I just set up a new docker server and added octofarm to it. I followed the guide for setting up the sever with docker compose. The error I am getting is:
05:05:33 0|OctoFarm  | 2022-11-05T05:05:33:  ERROR MESSAGE: cant find target folder... | /app/images
05:05:33 0|OctoFarm  | 2022-11-05T05:05:33: Error: EACCES: permission denied, open '../images/bg.jpg'

Attached is my log dump from docker and my docker-compose.yaml file.

[_octofarm_logs.txt](https://github.com/OctoFarm/OctoFarm/files/9943110/_octofarm_logs.txt)
[docker-compose.yaml.txt](https://github.com/OctoFarm/OctoFarm/files/9943114/docker-compose.yaml.txt)

I am very new to docker so forgive me if I missed something obvious.

### Steps taken to reproduce

added config from the website to docker-config.yaml and received the error immediately after

**Comment by NotExpectedYet** [comment]
Morning,

Yeah that's a lacking in my documentation. Internally the docker container uses the octofarm:octofarm user. 

You need to `sudo chmod 777 -r OctoFarm/` directory and it should boot with a restart of the container.

Edit: Please be aware that command gives write access for any user on that folder. Really you should create an OctoFarm user and give the folder permissions to that.

**Comment by SavvyRainbow** [comment]
Appreciate the response. that does seem to have fixed that problem but.... now there is another issue. attached is my current log. looks like it might be an issue with mongodb. I included my mongodb log just incase.
[_mongodb_logs (1).txt](https://github.com/OctoFarm/OctoFarm/files/9944217/_mongodb_logs.1.txt)
[_octofarm_logs.txt](https://github.com/OctoFarm/OctoFarm/files/9944219/_octofarm_logs.txt)

**Comment by NotExpectedYet** [comment]
Weird, its saying the username and password is wrong but your example looks correct

**Comment by SavvyRainbow** [comment]
I did nothing... but now it is working...

**Comment by NotExpectedYet** [comment]
Love it, glad it's working!
