### ISSUE TITLE
Update to NodeJS v14 LTS

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#266]
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - NodeJS Version [e.g. 13]
 - OctoFarm Version [e.g. 1.5.5.7]
 - OctoPrint Version [e.g. 1.4.1]
 - OctoPrint Plugins [e.g. bed visualiser, octoklipper, printtimegenius]

**Additional context**

**Comment by davidzwa** [comment]
@NotExpectedYet this is already on dev right now. Should it go to 1.1.13?

**Comment by NotExpectedYet** [comment]
> @NotExpectedYet this is already on dev right now. Should it go to 1.1.13?
> Or maybe we have to introduce 1.2 and work from there?

Is already on Dev, I just need to make some on the fly changes to the current website instructions. 

Gonna add update instructions too. Will sort from Friday then is fine for 1.1.13 when we've done all that.
