### ISSUE TITLE
UsageOverTime does not have index 0 when history is still empty

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#283]
Latest DEV version (partially with webpack, but it's not related) ;)

![image](https://user-images.githubusercontent.com/6005355/107862596-fbbdf700-6e4d-11eb-926a-4ebd47418b71.png)

dashboardRunner.js
```
  let usageOverTime = historyStatistics.history.usageOverTime;
  
  ...
  {
        seriesName: usageOverTime[0].name,
  }        
```

Couple of other places as well, please check thorougly!

**Comment by davidzwa** [comment]
Will be fixed in webpack release. Small ternary operator fix.

**Comment by NotExpectedYet** [comment]
Hmmm yeah that would probably break thinking about it. 

Another good catch. I've got a few hours this morning so I'll take a look at the webpack PR.
