### ISSUE TITLE
Typo in System panel (.snapshot instead of .snapshots)

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#284]
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Describe the bug**
Typo in property accessor `res.history.snapshot.onComplete`

**To Reproduce**
Look at:
```
          document.getElementById("snapOnComplete").checked =
            res.history.snapshot.onComplete;
```
Place debug breakpoint
Reload
See that `snapshots` looks like, but is not equal to, `snapshot` 

**Expected behavior**
No errah

**Screenshots**
![image](https://user-images.githubusercontent.com/6005355/107862873-4e001780-6e50-11eb-82bd-dffe21e37d7e.png)

**Versions (please complete the following information):**
Latest

**Additional context**
This is what typescript can prevent jk :)

**Comment by NotExpectedYet** [comment]
Good catch! I think a priority might be getting that webpack sorted what do you think?
