### ISSUE TITLE
Support Display Layer Progress

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#295]
Support Display Layer Progress Plugin. 

Should be "simple". 

Check for existence of plugin and update a key
If key exists then before a print is started call DLP API

**Comment by NotExpectedYet** [comment]
No stale

**Comment by davidzwa** [comment]
This work could use a bit of refinement.

A question I have is that the plugin has not been updated for 4 months meaning it has not been developer with OctoPrint 1.6 or 1.7 in mind. I would like to push them to support that.
https://github.com/OllisGit/OctoPrint-DisplayLayerProgress
https://plugins.octoprint.org/plugins/DisplayLayerProgress/
