### ISSUE TITLE
[FEATURE REQUEST] Filament Manager Improvements

### ISSUE THREAD

**Issue by tophattwaffle** [OctoFarm/OctoFarm#324]
The filament manager feels like it is missing some features that could make it more useful.

1. Can't add multiple spools at a time.
  Issue when I buy 10x of the same spool at once and want to add them all to the DB.

2. Can't change spool mid print.
  Using a filament runout sensor. Lots of my prints will trigger this as they can be larger. Without being able to update the spool when this occurs, the filament used data is lost.

Running the docker monolithic-latest: which I pulled down on 2/25/2021. It is running Octofarm 1.1.10

**Comment by davidzwa** [comment]
Ah my bad - we're supposed to make discussions for feature request. Copied and closed!
https://github.com/OctoFarm/OctoFarm/discussions/325
