### ISSUE TITLE
BG image not ignored, make it a fallback image within assets

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#351]
**Client or Server side error** 
EJS

**Describe the bug**
Image can be changed, but then it becomes a git change as the file is still tracked.
Change image file and you'll see.

**Solution**
Make the image a fallback image with some smart index + EJS rendering logic.

**Comment by NotExpectedYet** [comment]
One for 1.1.13 :) 

Will investigate a graceful way as currently is sat in CSS hard coded I believe.

**Comment by davidzwa** [comment]
Point the URL to a route and figure it out in ExpressJS :)
