### ISSUE TITLE
Spool Manager doesn't allow decimal prices

### ISSUE THREAD

**Issue by ksolomon** [OctoFarm/OctoFarm#358]
**Client or Server side error** 
Client

**Describe the bug**
Price field in Spool Manager won't allow decimal prices

**To Reproduce**
1. Go to Filament from top right menu
2. Click on Spool Manager
3. Enter price using a decimal (19.95 for example).
4. Field highlights red, error on hover reads "Please select a valid value. The two nearest values are 19 and 20"

**Expected behavior**
Price should be added as entered

**Screenshots**
(Sorry it's a camera shot...no way to screenshot the error on hover)

![photo_2021-03-08_11-13-27](https://user-images.githubusercontent.com/251996/110356335-bed5c200-7fff-11eb-8e19-1a1007d6c391.jpg)

**Versions (please complete the following information):**
 - NodeJS Version: 12.20.1
 - OctoFarm Version: 1.1.11
 - OctoPrint Version: N/A
 - OctoPrint Plugins: N/A

**Additional context**

**Comment by NotExpectedYet** [comment]
Ahh thanks for the screenshot. Is a quick fix so will get it sorted.
