### ISSUE TITLE
Monolithic image exposes UDP (not TCP)

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#359]
**Client or Server side error** 
Server monolithic latest

**Describe the bug**
Should not expose UDP but TCP or both.

**Comment by davidzwa** [comment]
I think the thought behind this was that exposing the port as UDP would fix SSDP, but it is my belief that this is not going to work. From past experiences the moby engine does not receive UDP multicasts, so multicast+UDP-based SSDP, mDNS or uPnP is not going to work unless the container is connected to userland network (--net=host) thus removing network isolation.
https://stackoverflow.com/questions/42422406/receive-udp-multicast-in-docker-container

I dont think service discovery is robust, but still it is vital to our users! 

- It needs a self-registration push-based approach using TCP/WS on OctoPrint with a plugin, as we spoke about earlier.
- (Alternative) SSDP relay in userland/host https://github.com/dgeelen/ssdp-bridge

**Comment by NotExpectedYet** [comment]
Let's call the man himself as this was made before the scan was a thing on OctoFarm. 

@Mearman what was your thought behind UDP?

**Comment by NotExpectedYet** [comment]
It's not rubust it's aweful, I was very limited with what I could actually do there. It does help scan a load straight in like so anyone not on docker must surely find it useful.

**Comment by Mearman** [comment]
I HAVE BEEN SUMMONED.

I'm not sure if I've got the correct end of the stick. Is the proposal to open ports for TCP on the monolithic image to allow scanning?

**Comment by NotExpectedYet** [comment]
> I HAVE BEEN SUMMONED.
> 
> I'm not sure if I've got the correct end of the stick. Is the proposal to open ports for TCP on the monolithic image to allow scanning?

More just why it was UDP in the first place than anything. But yeah we're planning to expose TCP or both. I'm personally unsure of the ramifications so just wanted to summon you to check :D

**Comment by davidzwa** [comment]
The issue arose when a user was directly instantiating the container without any port adjustments. Once his port was exposed as TCP, OctoFarm's site was accessible again.
The thing about UDP is a different problem, but Im really curious to see if we can figure out the cause or solutions! My knowledge is very limited, or Im just not aware of the do's and dont's.
