### ISSUE TITLE
Re-Organise the history.js file and cleanup 

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#366]
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Client or Server side error** 
Server side

Time to gut our this file. 

Proposing a "state" folder with modules there in for organisation.

**Comment by davidzwa** [comment]
+ dedupe thumbnail and file downloader functions

**Comment by davidzwa** [comment]
Will take over this issue as a next refactor/V2 wombo combo

**Comment by davidzwa** [comment]
This is now done on BigOne canary. Marking as fixed.

**Comment by davidzwa** [comment]
Marking as closed as this is not noticeable or should not be noticeable.
