### ISSUE TITLE
Remove config/db.js + migration + fully test 

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#373]
Server
- Update migration script from 1.1.x to 1.1.13 to create .env file if it does not exist with latest MONGO=${MongoUri}
- Startup script to create .env if not exists and **not in docker mode** (using the same function as in the migration script, but now without `db.js` as source and default MONGO conn string without authentication) + test mongo after + warn if conn fails
- Fix startup mongo conn test not dealing with auth error correctly
- Add warning/console instructions about new environment variable requiring MONGO to be defined, abort if it is not defined
- Remove db.js file from repo
- Regression Test: .env with MONGO in it created and found at all times for non-docker (do this in test folder + gitignore the resulting .env at that place)
- Test migration script: .env with MONGO in it created and equal to our default string in config/db.js (hardcoded)
- Regression Test2: .env with custom (f.e. auth) MONGO in it created when this is known as environment var (and env file didnt exist before)
- Regression Test3: .env with valid MONGO not updated when the environment var is different before merging with `dotenv`

**Comment by NotExpectedYet** [comment]
We could do the same for Port here?

**Comment by davidzwa** [comment]
Love it! Will mark a separate issue and add similar validation/migration scripts.

**Comment by NotExpectedYet** [comment]
> Love it! Will mark a separate issue and add similar validation/migration scripts.
Epic! I think the UI option can go bye bye as well personally.
