### ISSUE TITLE
Settings Memory pie chart svg error

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#378]
**Client**
![image](https://user-images.githubusercontent.com/6005355/111533970-b7cd5300-8767-11eb-8d98-e3baa1ecbc1b.png)
SVG errors or at least some NaN sizing properties.

Not a big problem, low prio as I see it.

**Comment by davidzwa** [comment]
![image](https://user-images.githubusercontent.com/6005355/111534148-f400b380-8767-11eb-86ff-0063358189b9.png)
OctoRAM NaN probably

**Comment by NotExpectedYet** [comment]
Deffo the NaN hmm weird I sorted all those. What system are you on? Windows?

**Comment by davidzwa** [comment]
Jep windhose always

**Comment by NotExpectedYet** [comment]
Consequence of webpack? Don't see how like that's that's a server side response thought I'd check.

**Comment by davidzwa** [comment]
I think it's a division by zero + some missing data

**Comment by NotExpectedYet** [comment]
Yeah deffo missing data, I will have to create a fall back and test on my windows box to see what's missing/changed as the value for total RAM should certainly be available. That system check isn't the most graceful thing in the world and needs a good cleanup/refactor itself.

**Comment by davidzwa** [comment]
`systemInfo.sysProcess.mem` is not set. That's

We have the following properties in that subsection:
```
pmem = 2.009567407507439
memVsz = 326780
memRss = 335716
```
I went for `memRss` as it is described to represent used memory. Oh btw, I left `mem` as fallback, so your situation wont break.

**Comment by davidzwa** [comment]
Fixed in PR #417 
![image](https://user-images.githubusercontent.com/6005355/114064982-77f71880-989a-11eb-985e-1d10621e8ba2.png)

**Comment by davidzwa** [comment]
Different error now, needs new issue
