### ISSUE TITLE
Update the API endpoint for the database URL 

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#380]
Not a priority but the database URL API endpoint the client uses currently pulls from the incorrect key as it wasn't grabbing from the new .env file method. 

Quick fix. 

### To better help the developer understand your 
issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Client or Server side error** 
Which part of the serve does this effect? If you don't know/client side then please add screenshots with the browser console "F12" open.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - NodeJS Version [e.g. 13]
 - OctoFarm Version [e.g. 1.5.5.7]
 - OctoPrint Version [e.g. 1.4.1]
 - OctoPrint Plugins [e.g. bed visualiser, octoklipper, printtimegenius]

**Additional context**

**Comment by davidzwa** [comment]
So it is using the dotenv config right now. 

- Are we sure we want to expose username/password like this?
- Is this system page admin only?
- Do we want to make it adjustable there? It could cause a booting problem, but then we do give some control back to users

**Comment by NotExpectedYet** [comment]
What do you mean username and password? 

The majority is admin user, I think the entire bottom panel doesn't show to a user permission. 

I'm not sure if it should be in the UI it was only there originally to help people change it but now we have environment it might not be needed what do you think?

**Comment by davidzwa** [comment]
> What do you mean username and password?

I think having an authenticated database is super important. I dont understand why MongoDB goes without by default.

> The majority is admin user, I think the entire bottom panel doesn't show to a user permission.

Good!

> I'm not sure if it should be in the UI it was only there originally to help people change it but now we have environment it might not be needed what do you think?

Will answer offline

**Comment by NotExpectedYet** [comment]
> > What do you mean username and password?
> 
> I think having an authenticated database is super important. I dont understand why MongoDB goes without by default.
> 
Up to the user, I run without Auth because it's all contained in its own segregated network. No idea on why mongo does it that way like.
