### ISSUE TITLE
Circular dependency error on OctoFarm startup.

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#381]
**Describe the bug**

**To Reproduce**
Start OctoFarm

![image](https://user-images.githubusercontent.com/61137988/111905793-5d711280-8a45-11eb-9c9e-4e2116c07c49.png)

**Comment by davidzwa** [comment]
I linked the PR because the warnings disappeared one by one through refactor and restructuring the require calls.
