### ISSUE TITLE
Make sure update notification can only been seen by admin user. 

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#386]
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Client or Server side error** 
Server

**Describe the bug**
Currently the update check that's run server side can be seen by any user using OctoFarm. This should at least be disabled for anyone who is not an admin. 

**Additional context**
Extra bonus points 20 pushups

**Comment by davidzwa** [comment]
@NotExpectedYet this has to go into 1.1.13 I guess or is it less prio?

**Comment by NotExpectedYet** [comment]
I'd say so, no idea on users / admin setup across my user base so rather be safe.
