### ISSUE TITLE
Memory SVG on System page incorrect for certain Unix and docker systems

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#429]
Server side

When fixing #378 I already noticed weird scaling and missing child property `mem`. Now the error is gone, but the calculation for non `memRss` calculations is off (I didnt change anything here).
Needs to be determined where the problem lies and rectified for that situation. I expect somehow `mem` is a different unit than kB (f.e. MB's or bytes).

**Comment by NotExpectedYet** [comment]
Gonna move to a later release. Needs some investigating and testing across multiple systems. I've never had anyone point out it was wrong before but the memory one is certainly off somehow on my unix system.

**Comment by davidzwa** [comment]
Not that big of a deal. The page works so thats good
