### ISSUE TITLE
FileManager: Cannot read property 'toFixed' of null

### ISSUE THREAD

**Issue by asd20752** [OctoFarm/OctoFarm#438]
**Client or Server side error** 
Server error
![Error octofarm](https://user-images.githubusercontent.com/11799746/115060897-b323c800-9ee8-11eb-94da-02d3f5af13af.png)

**Describe the bug**
The bug occurred when I added a Prussa MK3 printer to OctoFarm. There is alot of files on the printer which showed up in OctoPrint. 

**To Reproduce**
Do not know how to reproduse 

**Expected behavior**
To see all the files on the printer

**Screenshots**
![Error octofarm](https://user-images.githubusercontent.com/11799746/115060897-b323c800-9ee8-11eb-94da-02d3f5af13af.png)

**Versions**

Docker: 19.03.13
{
  "Id": "sha256:ffc588835399000ca916346b7398f8b4745d6b288185f29d28679a5a034c5462",
  "Digest": null,
  "RepoDigests": [
    "octofarm/octofarm@sha256:70f366079ab038078a51912729f4e133735b5d09f707a24b4587b74f1cd650b0"
  ],
  "Labels": {
    "org.opencontainers.image.created": "2021-03-05T07:50:06.839Z",
    "org.opencontainers.image.description": "OctoFarm is an  web server and client combination for unifying multiple instances of Octoprint. You can manage and monitor as many instances as you want from a single interface giving you full control over your 3D printer farm.",
    "org.opencontainers.image.licenses": "AGPL-3.0",
    "org.opencontainers.image.revision": "d5983dc8ca175c580380fb3585531bea6e280360",
    "org.opencontainers.image.source": "https://github.com/OctoFarm/OctoFarm",
    "org.opencontainers.image.title": "OctoFarm",
    "org.opencontainers.image.url": "https://github.com/OctoFarm/OctoFarm",
    "org.opencontainers.image.version": "master"
  }
}

 - OS: Zorin 15.3
 - (docker container) OctoFarm Version 1.1.12
 - (docker container) OctoPrint Version 1.5.3
 - Firmware: Prusa-Firmware 3.9.3 based on Marlin

**Additional context**
I suspect that there is something in the file names that might be filtered out, or alternatively a off by one error.

**Comment by NotExpectedYet** [comment]
It's because of the statistics generation in the background on the server. Your files don't seem to have come with a size throwing off the calculation. I'll check on that, and move the toFixed off the page so it's not an issue at the very least.
