### ISSUE TITLE
Re-input catch statements in updater logic

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#442]
I believe I incorrectly removed the stderr catch statements from the upgrade logic, if those failed for whatever reason they would just crash out the system so I will add them back in and do some further testing with that and get a PR ready if that's the case.

**Comment by davidzwa** [comment]
I would suggest in that case to catch specific errors + catch-all and grab out the right message to propagate to the UI. That will make sure that the expected errors are humanized

https://stackoverflow.com/questions/1433558/handling-specific-errors-in-javascript-think-exceptions#:~:text=Using%20try%2Dcatch%2Dfinally.,call%20to%20execute%20either%20way.
```
// ...
try {
  throwSpecificError();
} catch (e) {
  if (e.name == 'SpecificError') {
   // specific error
  } else {
    throw e; // let others bubble up
  }
}
```
