### ISSUE TITLE
Rate limit the reminder for update more

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#466]
- Description
Annoying! XD

Or disable completely if the user selects mark read. 

Later then yeah add reminder. 

- Repro

**Comment by davidzwa** [comment]
As the updater was in limbo state it could not update as we didnt have OCTOFARM_ALLOW_PRERELEASE_INSTALL defined as env variable, but constantly thought 'hey but prerelease is out'!

So the rate limiting... mark read should work fine now. Can always spend time on doing it, but I wonder if its really needed.
If we look at OctoPrint they spam you until you hit mark read anyway.

**Comment by NotExpectedYet** [comment]
> As the updater was in limbo state it could not update as we didnt have OCTOFARM_ALLOW_PRERELEASE_INSTALL defined as env variable, but constantly thought 'hey but prerelease is out'!
> 
> So the rate limiting... mark read should work fine now. Can always spend time on doing it, but I wonder if its really needed.
> If we look at OctoPrint they spam you until you hit mark read anyway.

Spamming till mark read is fine, but yeah tested and re-produced the fixes fine all golden.
