### ISSUE TITLE
Abort if less than Node 14 (f.e. 10 or 12)

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#478]
Add code which can compile in Node 12 to abort an OctoFarm installation in Node <14.
Had gm reporting the '?' operator failing for earlier node version in pm2 but it repeatedly continues

**Comment by NotExpectedYet** [comment]
Engines strict is no longer working that's why. 

Apparently it needs to be in npmrc file now. Will research more.

**Comment by davidzwa** [comment]
Ah and I guess continuous pm2 restarting is only temporary

**Comment by NotExpectedYet** [comment]
> Ah and I guess continuous pm2 restarting is only temporary

Think we need to add a --restart-delay for that one

https://pm2.keymetrics.io/docs/usage/restart-strategies/
