### ISSUE TITLE
Username not normalized and invariantly compared. Uniqueness constraints lacking. 

### ISSUE THREAD

**Issue by Nomad965** [OctoFarm/OctoFarm#515]
### Versions

* Your **OctoFarm version** (latest 1.1.13): 1.1.13
* Your **OctoPrint version** (latest 1.5.3): 1.6.0
* Docker or pm2: pm2
* **NodeJS version** 14 or 15 (not for docker): 14.16.1
* Operating System (f.e. Raspberry Pi OS, Ubuntu, Windows): Windows 10 Pro 64bit / OSBuild 19042.928
* OctoPrint Plugins (e.g. bed visualiser, octoklipper, printtimegenius): OctoDash, PrusaThumbnail

### Reproduction

* **Location** of the problem (choose Server, NodeJS, MongoDb database or local website) webgui
* Description of the problem: Cannot add new printer
* Steps needed to **reproduce** the problem. Register new user> setup new printer> No printer is available
* Expected behavior: Should be able to add new printer, browser brave and firefox same issue
![OF](https://user-images.githubusercontent.com/28869543/116629357-b17ee900-a959-11eb-9317-707aea8af940.png)
[octofarm_dump.zip](https://github.com/OctoFarm/OctoFarm/files/6402123/octofarm_dump.zip)

* (Optional) To avoid the problem I had to:

### OctoFarm Logs

If you've got access to the System screen it's better to just upload the log dump file as it will
contain all relevant information for the developers.

1) **OctoFarm Server logs** Add the system page logs .zip file (if you cant access it, upload your `./logs` folder content here)
2) **Console logs** in your browser.
   (How to: https://javascript.info/devtools)
3) **Screenshots**
   These are always effective, add screenshots to help explain your problem.

**Comment by NotExpectedYet** [comment]
Only the first user created can create printers. New users get the user key and cannot. There's a note on the register screen.

![image](https://user-images.githubusercontent.com/61137988/116648947-41cb2700-a976-11eb-8760-2d05df4ef7e8.png)

**Comment by Nomad965** [comment]
Hi James, thank you for the prompt reply, I only have one user set and not other user created.

**Comment by NotExpectedYet** [comment]
Hello! Your welcome. 

Hmm I tried to reproduce your issue before posting and my Administrator user is correctly created. 

There's a .env file inside your OctoFarm folder. Could you please try just appending some extra text onto the MONGO url something like the example below. This will create a new database. 

If the problem persists I'll probably need some of the logs out of your OctoFarm/logs folder.

```
MONGO=mongodb://127.0.0.1:27017/octofarmnew
```

**Comment by davidzwa** [comment]
Screenshots in discord, logs of current situation were attached by O P

**Comment by NotExpectedYet** [comment]
There's nothing in the logs sorry didn't notice you'd posted them had just woken up aha. Hopefully a new database resolves the issue.

**Comment by davidzwa** [comment]
James showed me the code where the error occurs, and I was able to get the same error as you @Nomad965. The problem is clear: the Administration group is not set to your user.

We have some possible ideas:
- does a new database fix it?
- could it be that 2 users were created per accident? Can you download https://www.mongodb.com/try/download/compass and check your octofarm users table?

**Comment by Nomad965** [comment]
Could this be the problem ?
Just delete one ?

![mngdb](https://user-images.githubusercontent.com/28869543/116723877-9f985700-a9e8-11eb-9ce3-710f38d80217.png)

**Comment by Nomad965** [comment]
Could this be the problem?

Just delete all of the users and redo again or just delete the non admin user ?
![mongdb](https://user-images.githubusercontent.com/28869543/116724342-382ed700-a9e9-11eb-9d7c-ceb0d53cfbbd.jpg)

**Comment by NotExpectedYet** [comment]
> Could this be the problem?
> 
> Just delete all of the users and redo again or just delete the non admin user ?
> ![mongdb](https://user-images.githubusercontent.com/28869543/116724342-382ed700-a9e9-11eb-9d7c-ceb0d53cfbbd.jpg)

Certainly is! Delete the user and you should be fine :) 

Thanks for getting back to us.

**Comment by Nomad965** [comment]
Ahhhhaa, now I see what went wrong, a mistake on my behalf, looks like I registered the Admin account under the username Nomad, when I tried to login the first time round I, used nomand with lowercase "n". 

The db does not identify the difference between uppercase and lowercase admins and treats them as one. So thinking when I did the 1st time registration, I did not pay attention to that, and registered again a new user with nomad, not knowing that the right username for admin was Nomad.

Just logged in now, and proceeding with the rest of the setup and testing.

Thank you very much for the help and support @NotExpectedYet @davidzwa 

Cheers..

**Comment by davidzwa** [comment]
This is awesome news Nomad. We know what to improve and you know how to work around it.

Win win!

**Comment by Nomad965** [comment]
Just something else I noticed not that it caused any login problems or authentication, when creating the api key under application / octoprint interface the assigned user is nomand with lower case n and the Admin user in octofarm is with capital N for nomad, the octofarm accepted the API key without any issues.

**Comment by NotExpectedYet** [comment]
> Just something else I noticed, not that it caused any login problems or authentication, when creating the api key under application / octoprint interface the assigned user is nomad with lower case n and the Admin user in octofarm is with capital N for nomad, the octofarm accepted the API key without any issues.

Those users are un-related. One is for OctoPrint and one for OctoFarm, they can be completely different.

**Comment by Nomad965** [comment]
Well noted, thank you for the clarifications.

**Comment by NotExpectedYet** [comment]
Bad stale bot
