### ISSUE TITLE
Printer map V1.2

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#526]
## Description

We have to think about:
- cleanup the printer map (davidzwa fork)
- define a predefined grouping system (blocks of 3x2, 2x2, 1x2, 1x1 etc, or none at all)
- (optional/alternative) drag and drop system to organize the blocks
- define a gallery system (multiple blocks)
- tabs with index numbers to switch between 'floors'
- printer group collection being used instead of single-value printer labels
- adjusting the tables to use these groups
- make the printer naming and URL settings 100% robust

**Comment by davidzwa** [comment]
@NotExpectedYet I dont think this is going to be ready soon as it is dependent on webpack (not a hard requirement, but it is very beneficial) and some backend cleanup work.

I would propose to move it to 1.2, what do you think?

**Comment by NotExpectedYet** [comment]
> @NotExpectedYet I dont think this is going to be ready soon as it is dependent on webpack (not a hard requirement, but it is very beneficial) and some backend cleanup work.
> 
> I would propose to move it to 1.2, what do you think?

Yeah no worries at all man, shift it into that project all good.

**Comment by NotExpectedYet** [comment]
Stale away!

**Comment by NotExpectedYet** [comment]
eurgh
