### ISSUE TITLE
OP printer settings dialog does not query fresh settings

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#532]
- Description
Upon editing settings we gotta have the latest settings set from OP. Fix that with an OP API call. Also add a loader to printer settings dialog.

- Repro
Open printer settings dialog.

**Comment by davidzwa** [comment]
It now queries the settings, but its not passed on to the UI.

```
09/05/2021, 10:09:18 | INFO | OctoFarm-State | Attempting to connect to API: api/system/commands | http://192.168.1.177 | timeout: 10000
09/05/2021, 10:09:18 | INFO | OctoFarm-State | Successfully grabbed System Information for...: http://192.168.1.177
09/05/2021, 10:09:35 | INFO | OctoFarm-State | Attempting to connect to API: api/settings | http://192.168.1.177 | timeout: 10000
09/05/2021, 10:09:35 | INFO | OctoFarm-State | Detected Pi Support!
09/05/2021, 10:09:35 | INFO | OctoFarm-State | Attempting to connect to API: api/plugin/pi_support | http://192.168.1.177 | timeout: 10000
09/05/2021, 10:09:35 | INFO | OctoFarm-State | Got from endpoint: data:{"model":"Raspberry Pi 4 Model B Rev 1.2","model_unrecommended":false,"throttle_state":{"current_issue":false,"current_overheat":false,"current_undervoltage":false,"past_issue":false,"past_overheat":false,"past_undervoltage":false,"raw_value
":-1}} |
```

**Comment by NotExpectedYet** [comment]
> It now queries the settings, but its not passed on to the UI.
> 
> ```
> 09/05/2021, 10:09:18 | INFO | OctoFarm-State | Attempting to connect to API: api/system/commands | http://192.168.1.177 | timeout: 10000
> 09/05/2021, 10:09:18 | INFO | OctoFarm-State | Successfully grabbed System Information for...: http://192.168.1.177
> 09/05/2021, 10:09:35 | INFO | OctoFarm-State | Attempting to connect to API: api/settings | http://192.168.1.177 | timeout: 10000
> 09/05/2021, 10:09:35 | INFO | OctoFarm-State | Detected Pi Support!
> 09/05/2021, 10:09:35 | INFO | OctoFarm-State | Attempting to connect to API: api/plugin/pi_support | http://192.168.1.177 | timeout: 10000
> 09/05/2021, 10:09:35 | INFO | OctoFarm-State | Got from endpoint: data:{"model":"Raspberry Pi 4 Model B Rev 1.2","model_unrecommended":false,"throttle_state":{"current_issue":false,"current_overheat":false,"current_undervoltage":false,"past_issue":false,"past_overheat":false,"past_undervoltage":false,"raw_value
> ":-1}} |
> ```

Should be able to sort without killing anything major. It just needs to call the cleaner again on the system one, or update the cached. Think I have a graceful work around after your comments anyway.

**Comment by NotExpectedYet** [comment]
Wasn't a cache update issue, it ran perfectly fine. It was me not pulling the correct information. Port preference comes from my getState command, so it needed to fire: getState, getSettings, getSystem. 

Has been fixed in latest PR. Just need to sort the button and write the test now.

**Comment by davidzwa** [comment]
Nice job! What in PrinterClean does it call, like a whole refresh?

**Comment by NotExpectedYet** [comment]
I shouldn't have changed printerClean here? If I did I'll undo it as I shouldn't need to. 

PrinterClean.generate function, it will run the cleaner for a single printer you pass to it so it now reruns that. In my tests the 500ms timer had mostly run already like by the time the updated settings had been called it was just to make sure.

**Comment by NotExpectedYet** [comment]
No your right I did aha. I tried to use the cache file, is that complete? It kept returning undefined for me so I updated the printer function to be able to return a single printer as well as the whole bunch.

**Comment by davidzwa** [comment]
Ah my goof there, no that's a work-in-progress :S
