### ISSUE TITLE
Filament / History Graphs stay "loading..." when no data presented if outside 30 day window.

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#538]
### Description of the problem

```bash
Not real dire, as depends how active someones farm is. Data is outside of 30 day window graphs still show "loading..."
```

### Reproduction of the problem

```bash
Go to graphs without that data in a 30 day window.
```

**Comment by NotExpectedYet** [comment]
@davidzwa this was fixed no?

**Comment by davidzwa** [comment]
I dont think it is. I was mainly busy with the data inside the 30 day interval. You were able to spot this bug outside it and I dont recall us fixing it

**Comment by NotExpectedYet** [comment]
> I dont think it is. I was mainly busy with the data inside the 30 day interval. You were able to spot this bug outside it and I dont recall us fixing it

I'll double check.

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/124348468-f3d6d780-dbe1-11eb-8ea3-f27ce3c48fbd.png)

Yeah fixed, well outside the 30 day window

**Comment by davidzwa** [comment]
Uhh or 90? Not sure right now

**Comment by NotExpectedYet** [comment]
> Uhh or 90? Not sure right now

Is it still 90? 

that's from dashboard, was taking it on face value you updated the variable name in the re-factor. If that's not the case then could still be a bug xD

![image](https://user-images.githubusercontent.com/61137988/124350274-96478880-dbeb-11eb-8d7d-cbaa808cc317.png)

**Comment by NotExpectedYet** [comment]
Think the dashboard charts need a check over. Get this when enabling the bottom ones. 

![image](https://user-images.githubusercontent.com/61137988/124350309-e4f52280-dbeb-11eb-92fc-7d1d59c6dcd2.png)

**Comment by davidzwa** [comment]
Yeah it was hard for me to test them. Rushed it a bit

**Comment by NotExpectedYet** [comment]
We have errors now though! 😁

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/124380545-17b71d80-dcb5-11eb-838c-7ee1bfd245a9.png)

Yep still brokey, need's to use the actual date ranges that are created, not -90 days haha.
