### ISSUE TITLE
History should show 'No history yet' when it is still loading

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#549]
### Description of the problem

The runner hasnt completed. This can already be returned to the browser as a "Calculating history information", and we can reload after it has completed automatically.

### Reproduction of the problem

```bash
Immediately load history after startup
```

![image](https://user-images.githubusercontent.com/6005355/117129054-8142aa80-ad9e-11eb-898c-e49041171b2d.png)

**Comment by NotExpectedYet** [comment]
Can you not close this time stale? dodo
