### ISSUE TITLE
`Offline after error` is colored yellow in printer management, resync shows Red Disconnected

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#555]
### OctoFarm Version

1.1.14-rc1 with webpack

### OctoPrint Version(s)

1.6.0

### pm2 or docker?

docker

### Operating System

Win10

### OctoPrint Plugins

None

### Location of the problem

NodeJS

### Description of the problem

When connecting to a printer which is having `udev` conflict issues OctoPrint says 'offline after error'. That's a problem of its own, but I would expect OctoFarm not to show **yellow** then.

Both the printers page and the printer map show the printer with yellow color instead. I would advise red.

### Steps taken to reproduce

```bash
1. Setup finicky `udev` rule (still figuring this out...)
2. Rescan ports on OctoPrint
3. Port detected
4. Port connect or AUTO connect fails with 
> 'State: Offline after error No more candidates to test, and no working port/baudrate combination detected.'
5. Try the same on OctoFarm, will say it is Offline with error but in yellow color.
...
```

### What did you expect to happen

```bash
Offline with error label on OctoFarm printer management to be red.
```

### To avoid the problem I had to

```bash
Make an issue and be amazed by this beautiful form without file uploads
```

**Comment by davidzwa** [comment]
The reason I mention this is because 'printing from SD' is also yellow, so Ive come to associate yellow with being OK.
![image](https://user-images.githubusercontent.com/6005355/117466949-872dbc80-af53-11eb-9ccd-8b7dd7915e58.png)

Finally, white on yellow isnt readable for this matte MTB3D trash 1-pixel screen

**Comment by NotExpectedYet** [comment]
I never supported printing from SD as I've never used it. I gather it's just falling back to a default. Yellow is generally warning.

**Comment by davidzwa** [comment]
Hmm mixing printing from SD and USB connection is a small hell. I've had to throw away prints because of (I think) my mistakes - I still have to figure out where this is caused.
Its a migration thing, a company must keep printing while setting up OctoFarm. I guess I should find more suitable moments where all the printers are done or offline.

Practical todo's
- The label for Offline after error could be changed to red
- The 'connection' switch is green, should be set to disconnected

**Comment by davidzwa** [comment]
### Description of the problem

```bash
Just some proactive coding we have to do as Websocket is in a temporary state (guess, pls validate before acting on it)
```


### Reproduction of the problem

```bash
Printer online
Connect OP
Power off printer
See yellow "Offline after error"
Refresh printer
Red "Disconnected" shows

The last 2 points can be acted on proactively immediately.
```

**Comment by NotExpectedYet** [comment]
So this was basically because I hadn't know about that error state. gathered it's new in 1.6.0. Before all errors started with a "Error!" string so I gather it's Gina trying to be more user focused in the error responses. Anymore crop up it's pretty easy to add the detection as you'll see on the PR. It's not really necessary in the websocket section apart from error's. From OP state as I override/change a few of those. IE, printer says "Disconnected" when you first boot up octoprint, then "Offline" after you connect and disconnect which seemed confusing to me so "Offline" -> "Disconnected" as well ha.
