### ISSUE TITLE
Develop Ansible recipe and trigger it from OctoFarm

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#559]
### Description of the problem

This is just a thought and totally not set in stone. 
```bash
Start experimenting with device setup and SSH, postponing security for reasons of not blocking creativity.
```

### Reproduction of the problem

```bash
...
```

**Comment by NotExpectedYet** [comment]
Take a look at tidelines he made some octoprint ones. Also OctoFarm I believe.

**Comment by davidzwa** [comment]
@tideline3d we summon you!

**Comment by tideline3d** [comment]
It's not in proper role layout, but it worked last I tried it. Hasn't been updated for any recent changes. 

https://github.com/tideline3d/octofarm_ansible/

**Comment by NotExpectedYet** [comment]
There's only node upgrade that's changed recently. So should work with minor midification to the role.
