### ISSUE TITLE
Latest development broke statistics

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#576]
### Description of the problem

```bash
UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'checkNested' before initialization

Have fixed in #545
```

### Reproduction of the problem

```bash
Open statistsics
```

**Comment by davidzwa** [comment]
Which file does this occur in? Cant reproduce.

**Comment by NotExpectedYet** [comment]
> Which file does this occur in? Cant reproduce.

Printer clean, was on my printer settings branch. Both fixed there.
