### ISSUE TITLE
sumValuesByGroup undefined

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#577]
### Description of the problem

```bash
UnhandledPromiseRejectionWarning: ReferenceError: sumValuesGroupByDate is not defined

Have fixed in #545
```

### Reproduction of the problem

```bash
Open statistics on latest dev
```

**Comment by davidzwa** [comment]
Cannot reproduce this. Which file does this error occur in?

**Comment by NotExpectedYet** [comment]
> Cannot reproduce this. Which file does this error occur in?

printerClean, might be a change I made on the printer settings branch. Dunno, just noticed it. Fixed it anyway, just needed "this." adding.

**Comment by davidzwa** [comment]
PrinterClean.sumValuesByGroup seems better to me, as it indicates that its static explicitly.

**Comment by NotExpectedYet** [comment]
> PrinterClean.sumValuesByGroup seems better to me, as it indicates that its static explicitly.

Is there a difference?

**Comment by davidzwa** [comment]
`this` can become wrongly defined for certain callback based code in static contexts and so sometimes care is needed. `PrinterClean.` can never go wrong.
If we ever change this class to be non-static, only `this.sumValuesByGroup` will work and not `PrinterClean.sumValuesByGroup`, so this is also a matter of being 100% clear in our code.

Dont get me wrong, in V2 it's all `this.` based, but this code isnt.

Btw, I will PR this separately to add tests, changelog and the fixes.
