### ISSUE TITLE
Printer Name seems to be overwritten even when provided

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#588]
### Description of the problem

```bash
...
```

### Reproduction of the problem

```bash
Add new printer, with name and it get's overwritten.
```

**Comment by davidzwa** [comment]
(Maybe not being able to connect is related and handy as a repro)

**Comment by NotExpectedYet** [comment]
> (Maybe not being able to connect to such a newly added printer is related and handy as a repro)

It "shouldn't" The name is set before that and only should be overwritten on a successful grab but will certainly check cheers.

**Comment by davidzwa** [comment]
I think this was my goof. Cannot reproduce, at least not on printersettings PR.
