### ISSUE TITLE
Clean up PrinterManagementRunner.js

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#612]
### Description of the problem

```bash
it's a mess and outdated jim!
```

### Reproduction of the problem

```bash
...
```

**Comment by NotExpectedYet** [comment]
- [ ] fix the spinner staying on logs
- [ ] refactor into modules

**Comment by davidzwa** [comment]
Both are done and stable on dev so closing for that reason.
https://github.com/OctoFarm/OctoFarm/tree/development/client_src/js/printerManager
