### ISSUE TITLE
Windows OS - Fix found for slow loading and response times

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#630]
### WINDOWS USERS ###
Dear Windows users, a fix has been found for slow loading times on Windows. We will fix this in the **release candidate** 1.2-rc1. This means it will be a while before it is stable.
I hope to release 1.2 soon, because all tests are green and performance is stable.

Cause:
System information loading CPU etc extremely slowly on Windows.

### Reproduction of the problem

Install on Windows, run and see the SystemRunner taking ages to load system information.

### Measurements
Before
![image](https://user-images.githubusercontent.com/6005355/122547037-e6411f80-d02f-11eb-9d5d-7cb759485498.png)
After
![image](https://user-images.githubusercontent.com/6005355/122547052-e93c1000-d02f-11eb-8df2-0b3ef37ee488.png)

About 5x faster server loading time to be expected

**Comment by davidzwa** [comment]
Clinic Flame report before
![image](https://user-images.githubusercontent.com/6005355/122547543-86974400-d030-11eb-8123-6cf457286dcc.png)
After removing system information
![image](https://user-images.githubusercontent.com/6005355/122547600-9adb4100-d030-11eb-932a-c266337a02b3.png)

**Comment by davidzwa** [comment]
The query times per info type. I've decided to drop cpu and osInfo
```
cpu: 2.079s
cpuSpeed: 0.216ms
cpuLoad: 0.248ms
memoryInfo: 89.856ms
uptime: 1.996ms
osInfo: 2.137s
systemProcesses: 344.157ms
fileSize: 90.77ms
```

After removing:
cpuSpeed: 0.482ms
cpuLoad: 1.51ms
memoryInfo: 93.6ms
uptime: 18.715ms
systemProcesses: 362.594ms
fileSize: 97.104ms

**Comment by davidzwa** [comment]
cpu property is redundant. Removing that.

**Comment by copc** [comment]
Can't wait it is so unusable right now for me.

**Comment by davidzwa** [comment]
@copc we are nearing a **release candidate** hopefully today, maybe tomorrow. Not guaranteed to be stable, but a lot better. Just needs some real testing.

Updating can only be done with git pull manually as this will be marked as a prerelease and the updater wont pick it up.

**Comment by NotExpectedYet** [comment]
> Can't wait it is so unusable right now for me.

It's on development if you fancy been a tester for it. It should work fine I think after the recent pushes.
