### ISSUE TITLE
Add FarmPi host version lookup and post on system page

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#643]
### Description of the problem

```bash
Check the FarmPi version on /system page
```

Query
/etc/farmpi_version

**Comment by mkevenaar** [comment]
Check if the file exists. If it does not exist, should we ignore the whole section or show `unknown`?

**Comment by davidzwa** [comment]
I was thinking of replacing the distro (Windows 10, Linux, or FarmPi). Does that have your fancy?

**Comment by mkevenaar** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/834643/122683181-ea229c80-d1fd-11eb-8638-ace6765d90a7.png)

**Comment by davidzwa** [comment]
Will be worked on, but tracked on DevOps.

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/146519317-dac62dc7-da5c-423d-b658-f68ef261883e.png)

Will be in V1.2 :) 

Just need to sort that extra space
