### ISSUE TITLE
`serverSettings.influxExport.active` index can fail at start - tests mostly

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#648]
### Description of the problem

```bash
This is a startup order problem mostly apparent during tests. It will fix itself with a dependency injection system in V2. For now: move to `app-core`
```

Related to #569  but more detailed and feasible.

### Reproduction of the problem

```bash
...
```

**Comment by NotExpectedYet** [comment]
I believe I may have inadvertently fixed this in the settings PR. Not checked haven't been able to reproduce locally.

**Comment by davidzwa** [comment]
> I believe I may have inadvertently fixed this in the settings PR. Not checked haven't been able to reproduce locally.

Personally I only see this in tests. It seems to be a race condition, or that's my escape argument for most of these things. I hope to move all startup calls to app.js or app-core.js one by one to see the impact

**Comment by davidzwa** [comment]
Marking this as fixed as the server settings are super reliable on canary.
