### ISSUE TITLE
New printer log is not shown vertically

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#659]
### Description of the problem

Shows horizontally

### Reproduction of the problem

![image](https://user-images.githubusercontent.com/6005355/123852625-cf96a480-d91c-11eb-93b5-ecbfbd055981.png)

**Comment by NotExpectedYet** [comment]
Just to add here for completeness the style isn't been replaced. It should be though as I'd rectified that on my local branch before committing those changes.

**Comment by davidzwa** [comment]
Rebuilt NPM and published package for NPM_ENV=production: problem's gone. Closing.
