### ISSUE TITLE
If the first timeout fails, the second doesn't seem to use the increase timeout value.

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#668]
### Description of the problem

User couldn't establish a connection to printer after RC upgrade. 

Logs said: timeout retrying in 5000. 

The initial timeout of 1000ms didn't work, and probably never worked. So I gather the setting to get the secondary timeout value which defaults to 10 seconds never got updated on the connection attempt.

**Comment by NotExpectedYet** [comment]
```

  async getUsers(printer, retry = false) {
    return this.getWithOptionalRetry(printer, apiUsers, retry);
  }

```

That should be retry = true

**Comment by davidzwa** [comment]
This was bound to happen once or twice. Good find!

**Comment by NotExpectedYet** [comment]
> This was bound to happen once or twice. Good find!

GM pointed it out like, man steamed ahead live in production aha. He's also said the files on one of his printers isn't syncing but awaiting more info on that.

**Comment by davidzwa** [comment]
By the by, interested if the timeout not increasing is the problem or not retrying.
As stated offline I dont think retrying would be the fix, slowly increasing timeout would.
And as also said offline, I hope to work towards a more robust timing manager solution

Have to investigate either way.

**Comment by NotExpectedYet** [comment]
> By the by, interested if the timeout not increasing is the problem or not retrying.
> As stated offline I dont think retrying would be the fix, slowly increasing timeout would.
> And as also said offline, I hope to work towards a more robust timing manager solution
> 
> Have to investigate either way.

Yeah I think it's that, just investigating now and what I presumed above is wrong after looking at state.js. You'd already passed the true flag for the retry's where applicable, so it is retying and I'm seeing the timeout increase to +9000.

**Comment by NotExpectedYet** [comment]
The fetchApiTimeout is being passed the secondary time out but it's not using it, it's still timing out at 1000ms.

**Comment by NotExpectedYet** [comment]
Yeah was the global API check not have retry. The rest already did. Nothing wrong with your functions or the original. 

Like you say could do with something to actually cancel that but it's work as it was on that PR now so I consider this issue fixed. Wrote my investigation up on the PR and what additional cleanups I did from some personal goofs a while back.
