### ISSUE TITLE
Mon calling OP start doesnt check if file is selected

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#710]
### Description of the problem
BigOne/canary allows starting print on a device which is connected but has no selected file. The Print button is enabled so to speak.
![image](https://user-images.githubusercontent.com/6005355/126879466-91d55cb5-1999-4ad7-a22d-fae5d972ac1a.png)

```bash
BigOne branch
```

![image](https://user-images.githubusercontent.com/6005355/126879408-52d6b7cc-81d6-4af2-911e-56c756285d43.png)
Couple of API requests failing when clicking print:
- API requests keep on going and nothing is stopping them/aborting the process
- printer manager doesnt check or fails to check whether a file is selected 

We have to check if this is a BigOne caused problem or a develop/canary client bug.

### Reproduction of the problem

Repro: BigOne/canary start print on a device which is connected but has no selected file.
Cant see any UI alerts, just the API errors above which are basically OP telling us this is incorrect.

My guess? `axios` being setup a bit too developer friendly and not user friendly.

**Comment by NotExpectedYet** [comment]
The 3 printhead calls has been around for a while. 

This looks like a canary problem, can't repro on dev. "Print" button is correctly disabled without a file selected. There's no UI alerts because it should be disconnected, which leads me to think a state isn't been passed to the client. 

Doubt it's axios considering it's not even on the octoprint client yet

**Comment by davidzwa** [comment]
The reason for the OP API errors was the feedrate and flowrate factor body values were `null`. That's ofc related to me hacking together the backend with stub values.
Would be nice if the OP client validates required variables in future
