### ISSUE TITLE
Set timezone from `.env` LOG_TIMEZONE=... used for the logger `Intl.DateTimeFormat` options

### ISSUE THREAD

**Issue by ldiegos** [OctoFarm/OctoFarm#715]
**Please point out the url of the documentation issue**
e.g. https://octofarm.net/installation#Docker

**Please describe the correct steps that should be updated on the documentation**
The log files from octofarm, seems to be always in GMT, and i'm in GMT+1 - Paris, Madrid. Could you explain or detail in a "guide" in the octofarm site how to change this?

**Additional context**
![image](https://user-images.githubusercontent.com/29803600/126946731-e7ef71a5-24c8-4b21-be9b-4c8dad8c424e.png)

**Comment by davidzwa** [comment]
To answer your question directly, we do not have this option without changing the code. That can change as it is quite an easy fix (at least for the logging format). In that case I kindly ask for your patience so we can apply that to the next release.

#### Changing the code (this is reverted when you update OctoFarm!)
In `server_src/lib/logger.js` we've set-up a formatter for dates. Find the code here:
https://github.com/OctoFarm/OctoFarm/blob/e99cabd3f27f3ab6e21c27f0da5e8e319c4a2751/server_src/lib/logger.js#L9
![image](https://user-images.githubusercontent.com/6005355/126956541-29d3d988-cf30-4b10-81f2-0afc2990ab8e.png)
We've manually enforced UTC there. If I change it the timezone value to "Europe/Amsterdam" the format changes to GMT+1/+2.

Europe/Madrid or Europe/Paris would result in the same +1/+2 offset.
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Hope that this temporarily offers a solution.

**Comment by ldiegos** [comment]
Thank you so much @davidzwa !!! 
Sure, i'm not in a hurry, i will wait as long as you need. 

I will stop updating the project when it start (i have a script to download the last version and start it) and i will change that line in the *.js

Again, thank you so much.

**Comment by NotExpectedYet** [comment]
Worth a .env variable for this?

**Comment by ldiegos** [comment]
Hi,
    What ever you want, but please, invest some minutes to create a guide or some notes in the octofarm web site.
Thank you so much!

**Comment by NotExpectedYet** [comment]
> Hi,
> What ever you want, but please, invest some minutes to create a guide or some notes in the octofarm web site. Avoiding to lose it when you update the project with the "git pull"
> 
> Thank you so much!
> Luis.

Sorry that was a question for david aha. 

Yeah that's what this will sort :)

**Comment by davidzwa** [comment]
@NotExpectedYet I'll answer just in case, adjusted the title to what my plan was.

**Comment by NotExpectedYet** [comment]
> @NotExpectedYet I'll answer just in case, adjusted the title to what my plan was.

I saw :)
