### ISSUE TITLE
Printer groups not working as intended

### ISSUE THREAD

**Issue by pat1121** [OctoFarm/OctoFarm#730]
### OctoFarm Version

1.1.13

### OctoPrint Version(s)

1.6.1

### pm2 or docker?

docker

### Operating System

Unraid

### OctoPrint Plugins

none used

### Location of the problem

Web Interface

### Description of the problem

```bash
...
When creating groups of printers, items named the same are replicated in the group dropdown.

Also, when selecting one of these groups, all printers disappear from the view.
```

### Steps taken to reproduce

```bash
1.Put 2 printers in the same group (ie Group 1)
2. 'Group 1' will appear in the filter menu twice
3. Selecting group 1 as a filter will make all printers disappear from the view
...
```

### What did you expect to happen

```bash
Only a single group to appear for each item (ie Group 1)
The printers inside that group to be on the screen after the 'group 1' filter is selected
```

### To avoid the problem I had to

```bash
have not figured out a way around the problem yet.
```

**Comment by pat1121** [comment]
![grouping issue](https://cdn.discordapp.com/attachments/709293261646200842/873167984053616650/unknown.png)

**Comment by NotExpectedYet** [comment]
Cheers for loggin that will get it sorted. Next release might be a while that includes the fix but can let you know when it hits development.

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/137588587-16e3acdb-df7d-4c4c-ab5c-9bccedda0da8.png)
 
woop
