### ISSUE TITLE
Font Color hard to read with some Octoprint UI Colors

### ISSUE THREAD

**Issue by doucettom** [OctoFarm/OctoFarm#839]
### Description of the problem

```bash
...
Blue has a greyish Font that is hard to read. I have yet to validated the other ones.
```

### Reproduction of the problem

```bash
...
```

**Comment by NotExpectedYet** [comment]
https://github.com/OctoFarm/OctoFarm/discussions/779

Added here

**Comment by NotExpectedYet** [comment]
@doucettom have a look out for v0.9.9-alpha.9

I decided to change my issues up a little bit. So If you've anymore on dev, feel free to open them here to be tracked :)
