### ISSUE TITLE
When window resized to be fairly small, current operations get really squashed.

### ISSUE THREAD

**Issue by npike** [OctoFarm/OctoFarm#871]
### OctoFarm Version

1.1.13-hotfix

### OctoPrint Version(s)

1.6.0

### pm2 or docker?

docker

### Operating System

Linux

### Location of the problem

Web Interface

### Description of the problem

```bash
I like to run Octofarm's "Current Operations" page in a small floating window on my work computer, but when shrunk to a "tall and skinny" window size the operations wrap weirdly.

See screenshot https://paste.pics/f6b66b2bb61dab7456bab58c4433e105
```

### Steps taken to reproduce

```bash
1. Navigation to Current Operations (two printers running)
2. Shrink window to be like 50x500
```

### What did you expect to happen

```bash
I hope that operations would make the best use of the available whitespace on the page, even when the window size is small.
```

### To avoid the problem I had to

```bash
...
```

**Comment by NotExpectedYet** [comment]
Hey thanks for reporting that, had no idea! 

Do you have any preference on how it should display it on a screen that size? Like I'd probably end up just showing it on a row similar how panel/camera currently stack, but I think that's actually small enough two might work. 

I'm thinking those buttons could do with some work as well, as I've added sorting to that panel in V1.2 so they'll probably be even more squished.
