### ISSUE TITLE
How are Update to 1.2.0 alpha 

### ISSUE THREAD

**Issue by tomtim00700** [OctoFarm/OctoFarm#884]
Octofarm is running on my raspberry pi very well, but the cameras are not every time activ
I will test the alpha, but i can not Update.

How can i update in ssh the 1.1.3. hotfix to 1.2.0 ?

**Comment by NotExpectedYet** [comment]
There's instructions here

https://docs.octofarm.net/installation/trying-alpha-versions.html

**Comment by NotExpectedYet** [comment]
Bugs I have listed and are known are here: 

https://github.com/OctoFarm/OctoFarm/projects/30

In the V1.2-ToDo and In Progress

**Comment by NotExpectedYet** [comment]
I will warn if you use the Filament manager then I'd wait because that is borked and currently been worked on for the next alpha :)

**Comment by tomtim00700** [comment]
Thank you... but after the install is the system not starting :( But i will test it in the next days agein. Thank you.

**Comment by NotExpectedYet** [comment]
Would need more information to help out further.

**Comment by NotExpectedYet** [comment]
Hello, 

The master version has now been updated with all the latest development work. V1.2 basically. 

I believe this should be resolved, so I'm going to close it. Please feel free to re-open after updating if that's not the case.
