### ISSUE TITLE
V1.2 - RC8 Issues - Please report here!

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#912]
### Description of the problem

Below are the issues found in V1.2-RC8 that are required to fix before V1.2 final release. 

- [x] Group view is still disabled due to needing a check through. 
- [x] Filament Manager plugin needs checking through fully
- [x] Websockets go stale and do not re-setup... something wrong with the ping/pong checker. 
- [x] Plugins fail on start up with already onboarded printer, succeed with rescan api - message isn't great... 
- [x] Non onboarded printers need to force a file sync
- [x] Non onboarded printers with filament manager plugin setup should force a filament resync. 
- [x] Broke automated file updating. - Due to changes with not overriding file name - File with spaces in the name only
- [x] Registration disables button but does nothing

- [x] Test the auto updater

**Comment by HappyRave** [comment]
Hi! I just discovered Octofarm and did a new install of V1.2-RC8 (it says 1.2.0-alpha.36 on the webpage). There seems to be an issue with the user registration step. Clicking on "Register" after filing all the fields disables the button, but nothing happens afterward. No console error, nothing relevant in the logs files, no user created.

**Comment by NotExpectedYet** [comment]
> Hi! I just discovered Octofarm and did a new install of V1.2-RC8 (it says 1.2.0-alpha.36 on the webpage). There seems to be an issue with the user registration step. Clicking on "Register" after filing all the fields disables the button, but nothing happens afterward. No console error, nothing relevant in the logs files, no user created.

Thanks for the report! Will take a look.

**Comment by NotExpectedYet** [comment]
> Hi! I just discovered Octofarm and did a new install of V1.2-RC8 (it says 1.2.0-alpha.36 on the webpage). There seems to be an issue with the user registration step. Clicking on "Register" after filing all the fields disables the button, but nothing happens afterward. No console error, nothing relevant in the logs files, no user created.

I've fixed and pushed this to development. Goofed the onSubmit, for an onClick doh!

**Comment by HappyRave** [comment]
Registration working now, thank you!
![Screenshot 2022-05-12 170009](https://user-images.githubusercontent.com/3417987/168105974-0599086d-2523-465a-9631-ac6a35a4104a.jpg)
It looks like I can't add any printer, the logs tell that there was an issue retrieving the user list. I tried Application API, User API and Global API (CORS enabled)

**Comment by NotExpectedYet** [comment]
> Registration working now, thank you! ![Screenshot 2022-05-12 170009](https://user-images.githubusercontent.com/3417987/168105974-0599086d-2523-465a-9631-ac6a35a4104a.jpg) It looks like I can't add any printer, the logs tell that there was an issue retrieving the user list. I tried Application API, User API and Global API (CORS enabled)

Needs to be User or Application, global won't work for websockets. If you've one user it's probably a timeout issue, are they on WiFi? You can increase it in System -> Server settings. 
![image](https://user-images.githubusercontent.com/61137988/168191153-49c45e70-a846-4d19-910f-ad05185c3c1f.png)

**Comment by HappyRave** [comment]
Clicking the "system" tab seems to just load indefinitely. I changed the settings directly in MongoDB and now acquiring the user list no longer timeouts, but return a "FetchError: request to http://octoprusa1.local/api/users failed, reason: getaddrinfo EAI_AGAIN octoprusa1.local".
I did try the url in the browser (same Windows 10 PC runing Octofarm) and get a succesful response from Octoprint.

**Comment by NotExpectedYet** [comment]
> Clicking the "system" tab seems to just load indefinitely. I changed the settings directly in MongoDB and now acquiring the user list no longer timeouts, but return a "FetchError: request to http://octoprusa1.local/api/users failed, reason: getaddrinfo EAI_AGAIN octoprusa1.local". I did try the url in the browser (same Windows 10 PC runing Octofarm) and get a succesful response from Octoprint.
> 
> Edit: using the IP address instead of the network name fixed this issue, so I guess there's an issue with DNS resolution

No trouble, yeah was about to suggest. mDNS doesn't work everywhere and I need to put a note about not using it as I've seen all sorts of issues caused by it. Would you mind getting me the logs? System tab shouldn't be failing and I'm wondering what's going on there as I couldn't reproduce with a fresh install.

**Comment by NotExpectedYet** [comment]
I am going to swap the timeout settings though. Those are literally for offline printers, and the old scan time issues that would hold up the queue with offline printers. Think I'll default that setting to max rather than a close min as that setting was hiding the error.
