### ISSUE TITLE
How to update to v1.2

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#959]
Due to some changes I made with V1.2's folder structure the in app update will fail to restart your OctoFarm instance. It's probably easier to just use the cli for now with the following commands. 

Make sure to run these from your "OctoFarm" folder

`git pull`
`pm2 stop OctoFarm`
`pm2 delete OctoFarm` 
`sudo npm install -g npm@latest`
`npm run install-server`
`npm start`

You should have a fresh OctoFarm service up and running. 

You will have to re-generate the pm2 startup scripts to have OctoFarm enabled on boot. 

Instructions here:
https://docs.octofarm.net/installation/setup-service.html

Please comment below with any issues so I can advise further. The outputs of `git status` and `pm2 logs` will help me advise better. 

Docker note: Update with your usual method

Filament Manager Plugin note: If you use filament manager plugin you will need Disable the plugin link in System -> Server -> Filament. Refresh the page, and then Re-Enable it in the same location. This will set you up with the correct format for your spools. 

~~Printers timing out note: Increase your timeout for the API in system -> Server -> Timeout. 5000ms should be enough. The old setting doesn't work very well and was more of a patch over network issues.~~ - Timeout issue was resolved in a later version.

**Comment by NotExpectedYet** [comment]
If your here because you used the auto updater inside the application then do the following to restore your service to working order: 
Change into the OctoFarm directory
`pm2 delete OctoFarm`
`npm start` 

You will again have to re-generate the pm2 start up script mentioned above.

**Comment by IHVD** [comment]
Let's say I did use the in-app update button and am now facing 
![image](https://user-images.githubusercontent.com/1199556/172832362-df87c947-e43f-482a-8c14-d088a2e93917.png)
and 
![image](https://user-images.githubusercontent.com/1199556/172832388-4a9cb31b-de40-4cf9-a989-f796636da8ff.png)
what can I do to get the farm up and running again?
can I overwrite this installation via the cli commands?

**Comment by NotExpectedYet** [comment]
> edit: i'm blind, octofarm is running again, thanks for the great tool :D

aha no worries and most welcome :D
