### ISSUE TITLE
Web UI is no longer able to be embedded with an iframe

### ISSUE THREAD

**Issue by e1miran** [OctoFarm/OctoFarm#965]
### OctoFarm Version

1.2

### OctoPrint Version(s)

1.8

### pm2 or docker?

docker

### Operating System

Debian

### Location of the problem

Web Interface

### Description of the problem

```markdown
Previous to 1.2 I had the web interface embedded using iframe in my home automation app (Home Assistant). Since 1.2 it looks like it is now set to not allow cross site iframe embedding. 

According to the browser console, the page "refused to display in a frame because it set 'X-Frame-Options' to 'sameorigin'". 

What file contains the 'X-Frame-Options' setting so that I can allow again as a workaround?
```

### Steps taken to reproduce

Embed in an iframe

### What did you expect to happen

View the page

### To avoid the problem I had to

No workaround

**Comment by NotExpectedYet** [comment]
I will revert this in v1.2.1 which I'm prepping now. 

In future there will be a .env variable for this to be configured.
