### ISSUE TITLE
cant connect to printers

### ISSUE THREAD

**Issue by br3jlm** [OctoFarm/OctoFarm#981]
### OctoFarm Version

1.2.2

### OctoPrint Version(s)

1.8.0

### pm2 or docker?

pm2

### Operating System

windows

### Location of the problem

Web Interface

### Description of the problem

```markdown
cant connect to printers
```

### Steps taken to reproduce

cant connect to printer

### What did you expect to happen

i be able to connect to printers and control them

### To avoid the problem I had to

[octofarm_dump-5-22-2022-11-29-36 AM.zip](https://github.com/OctoFarm/OctoFarm/files/8749727/octofarm_dump-5-22-2022-11-29-36.AM.zip)

**Comment by NotExpectedYet** [comment]
At the time of the logs though your timeout settings we're 1000ms, I think this is too short. Can you try and put this up to 10000 please?

**Comment by br3jlm** [comment]
Ok it was the operator.  All I needed to do was delete all instances and add them again 🤡

**Comment by NotExpectedYet** [comment]
> Ok it was the operator. All I needed to do was delete all instances and add them again clown_face

Glad it's working!
